services:
  mysqldb-prod:
    image: docker.io/mysql:5.7
    container_name: flight-sim-mysqldb-prod
    restart: unless-stopped
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=flight-sim
    ports:
      - 4307:3306
    volumes:
      - db-prod:/var/lib/mysql
    networks:
      - server-network

  nodejs-prod:
    container_name: flight-sim-nodejs-prod
    depends_on:
      - mysqldb-prod
    build: server/
    restart: unless-stopped
    ports:
      - 9080:8080
    environment:
      - DB_HOST=mysqldb-prod
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=flight-sim
      - DB_LOCAL_PORT=4307
      - DB_PORT=3306
      - WEB_PORT=8080
      - JWT_SECRET=secret
      - OWNER_USERNAME=admin
      - OWNER_PASSWORD=123456
      - OWNER_EMAIL=admin@flight-sim.local
    stdin_open: true
    tty: true
    networks:
      - server-network

  angular-prod:
    container_name: flight-sim-angular-prod
    build:
      context: client/
      args:
        - BUILD_CONFIG=production
        - BASE_HREF=/
    restart: unless-stopped
    ports:
      - 9082:80
    networks:
      - server-network

volumes:
  db-prod:

networks:
  server-network:
    driver: bridge
