#include "fft_test.hpp"
#include "initial_spectrum_wgsl.h"   // generated by CMake: inline const char* INITIAL_SPECTRUM_WGSL
#if defined(WEBGPU_BACKEND_WGPU)
#include <webgpu/wgpu.h>             // wgpuDevicePoll
#endif

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <vector>

namespace {

constexpr uint32_t SIZE = 128;   // FFT grid; must be a multiple of the 8x8 workgroup

// CPU-side mirrors of the WGSL uniform / storage structs (std140/std430-compatible:
// all scalar f32/u32, tightly packed).
struct ParamsGPU {
  uint32_t Size;
  float LengthScale, CutoffHigh, CutoffLow, GravityAcceleration, Depth;
};
struct SpectrumGPU {
  float scale, angle, spreadBlend, swell, alpha, peakOmega, gamma, shortWavesFade;
};

void pump(WGPUDevice device) {
#if defined(WEBGPU_BACKEND_WGPU)
  wgpuDevicePoll(device, true, nullptr);
#elif defined(WEBGPU_BACKEND_DAWN)
  wgpuDeviceTick(device);
#else
  (void)device;
#endif
}

WGPUBuffer makeBuffer(WGPUDevice d, uint64_t size, WGPUBufferUsageFlags usage) {
  WGPUBufferDescriptor bd = {};
  bd.size = size;
  bd.usage = usage;
  return wgpuDeviceCreateBuffer(d, &bd);
}

WGPUTexture makeTexture(WGPUDevice d, WGPUTextureFormat fmt, WGPUTextureUsageFlags usage) {
  WGPUTextureDescriptor td = {};
  td.usage = usage;
  td.dimension = WGPUTextureDimension_2D;
  td.size = { SIZE, SIZE, 1 };
  td.format = fmt;
  td.mipLevelCount = 1;
  td.sampleCount = 1;
  return wgpuDeviceCreateTexture(d, &td);
}

std::vector<uint8_t> readback(WGPUDevice device, WGPUBuffer buf, size_t size) {
  struct MapState { WGPUBufferMapAsyncStatus status; bool done; } st{ WGPUBufferMapAsyncStatus_Success, false };
  auto cb = [](WGPUBufferMapAsyncStatus status, void* ud) {
    auto* s = static_cast<MapState*>(ud); s->status = status; s->done = true;
  };
  wgpuBufferMapAsync(buf, WGPUMapMode_Read, 0, size, cb, &st);
  while (!st.done) pump(device);
  std::vector<uint8_t> out(size);
  if (st.status == WGPUBufferMapAsyncStatus_Success) {
    const void* src = wgpuBufferGetConstMappedRange(buf, 0, size);
    std::memcpy(out.data(), src, size);
    wgpuBufferUnmap(buf);
  } else {
    std::fprintf(stderr, "[fft-test] buffer map failed: status=%d\n", (int)st.status);
  }
  return out;
}

// CPU oracle for WavesData — mirrors the WGSL exactly, in float32.
void wavesDataCPU(const ParamsGPU& p, uint32_t x, uint32_t y, float out[4]) {
  const float PI = 3.1415926f;
  float deltaK = 2.0f * PI / p.LengthScale;
  float nx = (float)x - (float)p.Size / 2.0f;
  float nz = (float)y - (float)p.Size / 2.0f;
  float kx = nx * deltaK, kz = nz * deltaK;
  float kLength = std::sqrt(kx * kx + kz * kz);
  if (kLength <= p.CutoffHigh && kLength >= p.CutoffLow) {
    float omega = std::sqrt(p.GravityAcceleration * kLength * std::tanh(std::min(kLength * p.Depth, 20.0f)));
    out[0] = kx; out[1] = 1.0f / kLength; out[2] = kz; out[3] = omega;
  } else {
    out[0] = kx; out[1] = 1.0f; out[2] = kz; out[3] = 0.0f;
  }
}

} // namespace

bool runInitialSpectrumTest(WGPUDevice device, WGPUQueue queue) {
  std::printf("[fft-test] initial-spectrum compute + readback (Size=%u)\n", SIZE);

  // ── deterministic test inputs ──
  ParamsGPU params{};
  params.Size = SIZE;
  params.LengthScale = 250.0f;
  params.CutoffHigh = 1000.0f;
  params.CutoffLow = 0.001f;   // sends the exact-centre (k=0) texel to the else-branch (avoids 1/0)
  params.GravityAcceleration = 9.81f;
  params.Depth = 500.0f;

  SpectrumGPU spectra[2] = {};
  spectra[0] = { 1.0f, 0.3f, 0.8f, 0.3f, 0.0081f, 0.8f, 3.3f, 0.01f };
  spectra[1] = { 0.0f, 0.f, 0.f, 0.f, 0.f, 1.0f, 1.0f, 0.f };  // scale=0 → second lobe skipped

  // ── input buffers ──
  WGPUBuffer paramsBuf = makeBuffer(device, 32, WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst);
  wgpuQueueWriteBuffer(queue, paramsBuf, 0, &params, sizeof(params));
  WGPUBuffer spectrumBuf = makeBuffer(device, sizeof(spectra), WGPUBufferUsage_Storage | WGPUBufferUsage_CopyDst);
  wgpuQueueWriteBuffer(queue, spectrumBuf, 0, spectra, sizeof(spectra));

  // ── output storage textures (+ CopySrc for readback) ──
  WGPUTexture wavesTex = makeTexture(device, WGPUTextureFormat_RGBA32Float,
                                     WGPUTextureUsage_StorageBinding | WGPUTextureUsage_CopySrc);
  WGPUTexture h0kTex   = makeTexture(device, WGPUTextureFormat_RG32Float,
                                     WGPUTextureUsage_StorageBinding | WGPUTextureUsage_CopySrc);

  // ── noise input texture, filled with deterministic pseudo-noise ──
  WGPUTexture noiseTex = makeTexture(device, WGPUTextureFormat_RGBA32Float,
                                     WGPUTextureUsage_TextureBinding | WGPUTextureUsage_CopyDst);
  {
    std::vector<float> noise(SIZE * SIZE * 4, 0.0f);
    for (uint32_t y = 0; y < SIZE; ++y)
      for (uint32_t x = 0; x < SIZE; ++x) {
        uint32_t h = x * 374761393u + y * 668265263u;
        h = (h ^ (h >> 13)) * 1274126177u;
        float a = ((h & 0xffffu) / 65535.0f) * 2.0f - 1.0f;
        float b = (((h >> 16) & 0xffffu) / 65535.0f) * 2.0f - 1.0f;
        size_t i = (size_t)(y * SIZE + x) * 4;
        noise[i + 0] = a; noise[i + 1] = b;
      }
    WGPUImageCopyTexture dst = {};
    dst.texture = noiseTex; dst.aspect = WGPUTextureAspect_All;
    WGPUTextureDataLayout layout = {};
    layout.bytesPerRow = SIZE * 16; layout.rowsPerImage = SIZE;
    WGPUExtent3D ext = { SIZE, SIZE, 1 };
    wgpuQueueWriteTexture(queue, &dst, noise.data(), noise.size() * sizeof(float), &layout, &ext);
  }

  WGPUTextureView wavesView = wgpuTextureCreateView(wavesTex, nullptr);
  WGPUTextureView h0kView   = wgpuTextureCreateView(h0kTex, nullptr);
  WGPUTextureView noiseView = wgpuTextureCreateView(noiseTex, nullptr);

  // ── shader module (the WGSL, verbatim from the client) ──
  WGPUShaderModuleWGSLDescriptor wgsl = {};
  wgsl.chain.sType = WGPUSType_ShaderModuleWGSLDescriptor;
  wgsl.code = INITIAL_SPECTRUM_WGSL;
  WGPUShaderModuleDescriptor smd = {};
  smd.nextInChain = &wgsl.chain;
  WGPUShaderModule module = wgpuDeviceCreateShaderModule(device, &smd);
  if (!module) { std::fprintf(stderr, "[fft-test] shader module creation failed\n"); return false; }

  // ── bind group layout: bindings 1,2,4,5,6 (exactly as the WGSL declares) ──
  WGPUBindGroupLayoutEntry ble[5] = {};
  ble[0].binding = 1; ble[0].visibility = WGPUShaderStage_Compute;
  ble[0].storageTexture.access = WGPUStorageTextureAccess_WriteOnly;
  ble[0].storageTexture.format = WGPUTextureFormat_RGBA32Float;
  ble[0].storageTexture.viewDimension = WGPUTextureViewDimension_2D;
  ble[1].binding = 2; ble[1].visibility = WGPUShaderStage_Compute;
  ble[1].storageTexture.access = WGPUStorageTextureAccess_WriteOnly;
  ble[1].storageTexture.format = WGPUTextureFormat_RG32Float;
  ble[1].storageTexture.viewDimension = WGPUTextureViewDimension_2D;
  ble[2].binding = 4; ble[2].visibility = WGPUShaderStage_Compute;
  ble[2].texture.sampleType = WGPUTextureSampleType_UnfilterableFloat;
  ble[2].texture.viewDimension = WGPUTextureViewDimension_2D;
  ble[2].texture.multisampled = false;
  ble[3].binding = 5; ble[3].visibility = WGPUShaderStage_Compute;
  ble[3].buffer.type = WGPUBufferBindingType_Uniform;
  ble[4].binding = 6; ble[4].visibility = WGPUShaderStage_Compute;
  ble[4].buffer.type = WGPUBufferBindingType_ReadOnlyStorage;

  WGPUBindGroupLayoutDescriptor bgld = {};
  bgld.entryCount = 5; bgld.entries = ble;
  WGPUBindGroupLayout bgl = wgpuDeviceCreateBindGroupLayout(device, &bgld);

  WGPUPipelineLayoutDescriptor pld = {};
  pld.bindGroupLayoutCount = 1; pld.bindGroupLayouts = &bgl;
  WGPUPipelineLayout pl = wgpuDeviceCreatePipelineLayout(device, &pld);

  WGPUComputePipelineDescriptor cpd = {};
  cpd.layout = pl;
  cpd.compute.module = module;
  cpd.compute.entryPoint = "calculateInitialSpectrum";
  WGPUComputePipeline pipeline = wgpuDeviceCreateComputePipeline(device, &cpd);
  if (!pipeline) { std::fprintf(stderr, "[fft-test] compute pipeline creation failed (WGSL rejected?)\n"); return false; }

  // ── bind group ──
  WGPUBindGroupEntry bge[5] = {};
  bge[0].binding = 1; bge[0].textureView = wavesView;
  bge[1].binding = 2; bge[1].textureView = h0kView;
  bge[2].binding = 4; bge[2].textureView = noiseView;
  bge[3].binding = 5; bge[3].buffer = paramsBuf; bge[3].size = 32;
  bge[4].binding = 6; bge[4].buffer = spectrumBuf; bge[4].size = sizeof(spectra);
  WGPUBindGroupDescriptor bgd = {};
  bgd.layout = bgl; bgd.entryCount = 5; bgd.entries = bge;
  WGPUBindGroup bindGroup = wgpuDeviceCreateBindGroup(device, &bgd);

  // ── readback buffers (row pitch is already 256-aligned: 128*16=2048, 128*8=1024) ──
  const size_t wavesBytes = (size_t)SIZE * SIZE * 16;
  const size_t h0kBytes   = (size_t)SIZE * SIZE * 8;
  WGPUBuffer wavesRead = makeBuffer(device, wavesBytes, WGPUBufferUsage_CopyDst | WGPUBufferUsage_MapRead);
  WGPUBuffer h0kRead   = makeBuffer(device, h0kBytes,   WGPUBufferUsage_CopyDst | WGPUBufferUsage_MapRead);

  // ── encode: compute pass, then copy both storage textures to readback buffers ──
  WGPUCommandEncoder enc = wgpuDeviceCreateCommandEncoder(device, nullptr);
  WGPUComputePassEncoder pass = wgpuCommandEncoderBeginComputePass(enc, nullptr);
  wgpuComputePassEncoderSetPipeline(pass, pipeline);
  wgpuComputePassEncoderSetBindGroup(pass, 0, bindGroup, 0, nullptr);
  wgpuComputePassEncoderDispatchWorkgroups(pass, SIZE / 8, SIZE / 8, 1);
  wgpuComputePassEncoderEnd(pass);

  auto copyTexToBuf = [&](WGPUTexture tex, WGPUBuffer buf, uint32_t bpr) {
    WGPUImageCopyTexture src = {}; src.texture = tex; src.aspect = WGPUTextureAspect_All;
    WGPUImageCopyBuffer dst = {}; dst.buffer = buf; dst.layout.bytesPerRow = bpr; dst.layout.rowsPerImage = SIZE;
    WGPUExtent3D ext = { SIZE, SIZE, 1 };
    wgpuCommandEncoderCopyTextureToBuffer(enc, &src, &dst, &ext);
  };
  copyTexToBuf(wavesTex, wavesRead, SIZE * 16);
  copyTexToBuf(h0kTex,   h0kRead,   SIZE * 8);

  WGPUCommandBuffer cmd = wgpuCommandEncoderFinish(enc, nullptr);
  wgpuQueueSubmit(queue, 1, &cmd);
  pump(device);

  // ── verify WavesData against the CPU oracle ──
  std::vector<uint8_t> wavesRaw = readback(device, wavesRead, wavesBytes);
  const float* waves = reinterpret_cast<const float*>(wavesRaw.data());
  int mism = 0, printed = 0; double maxErr = 0.0;
  for (uint32_t y = 0; y < SIZE; ++y)
    for (uint32_t x = 0; x < SIZE; ++x) {
      float expect[4]; wavesDataCPU(params, x, y, expect);
      const float* got = &waves[(size_t)(y * SIZE + x) * 4];
      for (int c = 0; c < 4; ++c) {
        float diff = std::fabs(got[c] - expect[c]);
        float tol = 1e-2f + 1e-3f * std::fabs(expect[c]);
        if (std::isfinite(diff) && diff > maxErr) maxErr = diff;
        if (diff > tol) {
          ++mism;
          if (printed < 4) {
            std::printf("[fft-test]   mismatch @ (%u,%u).%d expect=%.6g got=%.6g\n", x, y, c, expect[c], got[c]);
            ++printed;
          }
        }
      }
    }
  bool wavesPass = (mism == 0);
  std::printf("[fft-test] WavesData: %s — %d/%u components mismatched, max abs err %.3g\n",
              wavesPass ? "PASS" : "FAIL", mism, SIZE * SIZE * 4, maxErr);

  // ── sanity-check H0K (JONSWAP × noise path): all finite, some non-zero energy ──
  std::vector<uint8_t> h0kRaw = readback(device, h0kRead, h0kBytes);
  const float* h0k = reinterpret_cast<const float*>(h0kRaw.data());
  int nonFinite = 0, nonZero = 0;
  for (uint32_t i = 0; i < SIZE * SIZE * 2; ++i) {
    if (!std::isfinite(h0k[i])) ++nonFinite;
    else if (h0k[i] != 0.0f) ++nonZero;
  }
  bool h0kPass = (nonFinite == 0 && nonZero > 0);
  std::printf("[fft-test] H0K: %s — %d non-finite, %d non-zero of %u\n",
              h0kPass ? "PASS" : "FAIL", nonFinite, nonZero, SIZE * SIZE * 2);

  // ── teardown ──
  wgpuCommandBufferRelease(cmd);
  wgpuComputePassEncoderRelease(pass);
  wgpuCommandEncoderRelease(enc);
  wgpuBufferRelease(wavesRead); wgpuBufferRelease(h0kRead);
  wgpuBindGroupRelease(bindGroup);
  wgpuComputePipelineRelease(pipeline);
  wgpuPipelineLayoutRelease(pl);
  wgpuBindGroupLayoutRelease(bgl);
  wgpuShaderModuleRelease(module);
  wgpuTextureViewRelease(wavesView); wgpuTextureViewRelease(h0kView); wgpuTextureViewRelease(noiseView);
  wgpuTextureRelease(wavesTex); wgpuTextureRelease(h0kTex); wgpuTextureRelease(noiseTex);
  wgpuBufferRelease(paramsBuf); wgpuBufferRelease(spectrumBuf);

  bool allPass = wavesPass && h0kPass;
  std::printf("[fft-test] RESULT: %s\n", allPass ? "PASS — WGSL runs natively and reads back correctly" : "FAIL");
  return allPass;
}
