// sail-sim native client — Phase 0 spike: Dawn (WebGPU) device bringup + clear-colour loop.
//
// This is the smallest program that proves the PORTING.md thesis on real hardware:
// a Dawn-backed WebGPU device, running on D3D12 (Windows) or Metal (macOS), driving a
// swapchain. It prints the resolved backend so you can see D3D12/Metal/Vulkan at a glance.
//
// The WebGPU C API (webgpu.h) is version-sensitive. This file targets the "classic"
// callback style shipped by the eliemichel/WebGPU-distribution `dawn` branch, where
// requestAdapter/requestDevice resolve their callbacks synchronously. If your pinned
// header differs, the two request helpers below and the surface-status check are the
// only spots likely to need a one-line reconcile — see native/README.md.

#include <webgpu/webgpu.h>
#if defined(WEBGPU_BACKEND_WGPU)
#include <webgpu/wgpu.h>   // wgpu-native extensions (e.g. wgpuDevicePoll)
#endif
#include <glfw3webgpu.h>
#include <GLFW/glfw3.h>

#include <algorithm>
#include <cstdio>
#include <cstdlib>

#define GLM_FORCE_DEPTH_ZERO_TO_ONE   // WebGPU clip-space Z is [0,1], like D3D/Metal
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

#include <string>

#include "stb_image_write.h"

#include "fft_test.hpp"
#include "gltf_mesh.hpp"
#include "ocean_fft.hpp"
#include "wave.hpp"
#include "mesh_wgsl.h"            // generated by CMake: inline const char* MESH_WGSL
#include "ocean_surface_wgsl.h"  // generated by CMake: inline const char* OCEAN_SURFACE_WGSL

// ── async request helpers (resolve synchronously on Dawn/wgpu in this distribution) ──

static WGPUAdapter requestAdapterSync(WGPUInstance instance, const WGPURequestAdapterOptions* options) {
  struct Result { WGPUAdapter adapter = nullptr; bool done = false; } result;
  auto onAdapter = [](WGPURequestAdapterStatus status, WGPUAdapter adapter,
                      char const* message, void* userdata) {
    auto* r = static_cast<Result*>(userdata);
    if (status == WGPURequestAdapterStatus_Success) r->adapter = adapter;
    else std::fprintf(stderr, "[spike] requestAdapter failed: %s\n", message ? message : "(no message)");
    r->done = true;
  };
  wgpuInstanceRequestAdapter(instance, options, onAdapter, &result);
  // If a future header makes this genuinely async, pump events here instead of asserting.
  if (!result.done) std::fprintf(stderr, "[spike] requestAdapter did not resolve synchronously\n");
  return result.adapter;
}

static WGPUDevice requestDeviceSync(WGPUAdapter adapter, const WGPUDeviceDescriptor* descriptor) {
  struct Result { WGPUDevice device = nullptr; bool done = false; } result;
  auto onDevice = [](WGPURequestDeviceStatus status, WGPUDevice device,
                     char const* message, void* userdata) {
    auto* r = static_cast<Result*>(userdata);
    if (status == WGPURequestDeviceStatus_Success) r->device = device;
    else std::fprintf(stderr, "[spike] requestDevice failed: %s\n", message ? message : "(no message)");
    r->done = true;
  };
  wgpuAdapterRequestDevice(adapter, descriptor, onDevice, &result);
  if (!result.done) std::fprintf(stderr, "[spike] requestDevice did not resolve synchronously\n");
  return result.device;
}

static void onDeviceError(WGPUErrorType type, char const* message, void*) {
  std::fprintf(stderr, "[spike] uncaptured device error (%d): %s\n",
               (int)type, message ? message : "(no message)");
}

static const WGPUTextureFormat kDepthFormat = WGPUTextureFormat_Depth24Plus;

// A framebuffer-sized depth texture, recreated on resize.
static WGPUTexture makeDepthTexture(WGPUDevice device, uint32_t w, uint32_t h) {
  WGPUTextureDescriptor td = {};
  td.usage = WGPUTextureUsage_RenderAttachment;
  td.dimension = WGPUTextureDimension_2D;
  td.size = { w, h, 1 };
  td.format = kDepthFormat;
  td.mipLevelCount = 1;
  td.sampleCount = 1;
  return wgpuDeviceCreateTexture(device, &td);
}

// Uniforms uploaded per frame: clip matrix, model matrix (for normals + world
// position), and the camera position (for the PBR view vector).
struct MeshUniforms {
  glm::mat4 mvp;
  glm::mat4 model;
  glm::vec4 eye;
};

// A depth-tested, PBR-shaded mesh (glTF-loaded or the fallback cube). Holds the
// pipeline, buffers, decoded textures, and one bind group per texture; draws as a
// sequence of submeshes, each selecting its material's base-colour texture.
struct Mesh {
  WGPURenderPipeline           pipeline;
  WGPUBuffer                   vbuf, ibuf, uniformBuf;
  WGPUShaderModule             module;
  WGPUSampler                  sampler;
  std::vector<WGPUTexture>     textures;     // decoded maps + 1x1 white + flat-normal defaults
  std::vector<WGPUTextureView> views;        // aligned with textures
  std::vector<WGPUBindGroup>   bindGroups;   // one per submesh
  std::vector<Submesh>         submeshes;
};

static Mesh createMesh(WGPUDevice device, WGPUQueue queue, WGPUTextureFormat colorFormat, const MeshData& data) {
  Mesh mesh;
  mesh.submeshes = data.submeshes;

  WGPUBufferDescriptor vbd = {};
  vbd.usage = WGPUBufferUsage_Vertex | WGPUBufferUsage_CopyDst;
  vbd.size = data.vertices.size() * sizeof(float);
  mesh.vbuf = wgpuDeviceCreateBuffer(device, &vbd);
  wgpuQueueWriteBuffer(queue, mesh.vbuf, 0, data.vertices.data(), vbd.size);

  WGPUBufferDescriptor ibd = {};
  ibd.usage = WGPUBufferUsage_Index | WGPUBufferUsage_CopyDst;
  ibd.size = data.indices.size() * sizeof(uint32_t);
  mesh.ibuf = wgpuDeviceCreateBuffer(device, &ibd);
  wgpuQueueWriteBuffer(queue, mesh.ibuf, 0, data.indices.data(), ibd.size);

  WGPUBufferDescriptor ubd = {};
  ubd.usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst; ubd.size = sizeof(MeshUniforms);
  mesh.uniformBuf = wgpuDeviceCreateBuffer(device, &ubd);

  WGPUShaderModuleWGSLDescriptor wgsl = {};
  wgsl.chain.sType = WGPUSType_ShaderModuleWGSLDescriptor;
  wgsl.code = MESH_WGSL;
  WGPUShaderModuleDescriptor smd = {};
  smd.nextInChain = &wgsl.chain;
  mesh.module = wgpuDeviceCreateShaderModule(device, &smd);

  // bind group layout: uniform (b0), base/normal/metal-rough textures (b1-3), sampler (b4)
  WGPUBindGroupLayoutEntry ble[5] = {};
  ble[0].binding = 0; ble[0].visibility = WGPUShaderStage_Vertex | WGPUShaderStage_Fragment;
  ble[0].buffer.type = WGPUBufferBindingType_Uniform;
  for (int i = 1; i <= 3; ++i) {
    ble[i].binding = (uint32_t)i; ble[i].visibility = WGPUShaderStage_Fragment;
    ble[i].texture.sampleType = WGPUTextureSampleType_Float;
    ble[i].texture.viewDimension = WGPUTextureViewDimension_2D;
  }
  ble[4].binding = 4; ble[4].visibility = WGPUShaderStage_Fragment;
  ble[4].sampler.type = WGPUSamplerBindingType_Filtering;
  WGPUBindGroupLayoutDescriptor bgld = {};
  bgld.entryCount = 5; bgld.entries = ble;
  WGPUBindGroupLayout bgl = wgpuDeviceCreateBindGroupLayout(device, &bgld);

  WGPUPipelineLayoutDescriptor pld = {};
  pld.bindGroupLayoutCount = 1; pld.bindGroupLayouts = &bgl;
  WGPUPipelineLayout pl = wgpuDeviceCreatePipelineLayout(device, &pld);

  WGPUVertexAttribute attrs[5] = {};
  attrs[0].format = WGPUVertexFormat_Float32x3; attrs[0].offset = 0;                  attrs[0].shaderLocation = 0; // position
  attrs[1].format = WGPUVertexFormat_Float32x3; attrs[1].offset = 3  * sizeof(float); attrs[1].shaderLocation = 1; // normal
  attrs[2].format = WGPUVertexFormat_Float32x2; attrs[2].offset = 6  * sizeof(float); attrs[2].shaderLocation = 2; // uv
  attrs[3].format = WGPUVertexFormat_Float32x3; attrs[3].offset = 8  * sizeof(float); attrs[3].shaderLocation = 3; // albedo
  attrs[4].format = WGPUVertexFormat_Float32x2; attrs[4].offset = 11 * sizeof(float); attrs[4].shaderLocation = 4; // metallic, roughness
  WGPUVertexBufferLayout vbl = {};
  vbl.arrayStride = kFloatsPerVertex * sizeof(float);
  vbl.stepMode = WGPUVertexStepMode_Vertex;
  vbl.attributeCount = 5; vbl.attributes = attrs;

  WGPUDepthStencilState ds = {};
  ds.format = kDepthFormat;
  ds.depthWriteEnabled = true;
  ds.depthCompare = WGPUCompareFunction_Less;
  ds.stencilFront.compare = WGPUCompareFunction_Always;
  ds.stencilFront.failOp = WGPUStencilOperation_Keep;
  ds.stencilFront.depthFailOp = WGPUStencilOperation_Keep;
  ds.stencilFront.passOp = WGPUStencilOperation_Keep;
  ds.stencilBack = ds.stencilFront;
  ds.stencilReadMask = 0xFFFFFFFFu; ds.stencilWriteMask = 0xFFFFFFFFu;

  WGPUColorTargetState target = {};
  target.format = colorFormat;
  target.writeMask = WGPUColorWriteMask_All;
  WGPUFragmentState frag = {};
  frag.module = mesh.module; frag.entryPoint = "fs_main";
  frag.targetCount = 1; frag.targets = &target;

  WGPURenderPipelineDescriptor rpd = {};
  rpd.layout = pl;
  rpd.vertex.module = mesh.module;
  rpd.vertex.entryPoint = "vs_main";
  rpd.vertex.bufferCount = 1; rpd.vertex.buffers = &vbl;
  rpd.primitive.topology = WGPUPrimitiveTopology_TriangleList;
  rpd.primitive.frontFace = WGPUFrontFace_CCW;
  rpd.primitive.cullMode = WGPUCullMode_None;   // depth test handles occlusion
  rpd.depthStencil = &ds;
  rpd.multisample.count = 1;
  rpd.multisample.mask = 0xFFFFFFFFu;
  rpd.fragment = &frag;
  mesh.pipeline = wgpuDeviceCreateRenderPipeline(device, &rpd);
  wgpuPipelineLayoutRelease(pl);

  // linear, repeating sampler
  WGPUSamplerDescriptor sd = {};
  sd.addressModeU = WGPUAddressMode_Repeat;
  sd.addressModeV = WGPUAddressMode_Repeat;
  sd.addressModeW = WGPUAddressMode_Repeat;
  sd.magFilter = WGPUFilterMode_Linear;
  sd.minFilter = WGPUFilterMode_Linear;
  sd.mipmapFilter = WGPUMipmapFilterMode_Nearest;
  sd.lodMinClamp = 0.0f; sd.lodMaxClamp = 1.0f; sd.maxAnisotropy = 1;
  mesh.sampler = wgpuDeviceCreateSampler(device, &sd);

  // Upload decoded textures (sRGB for base colour, linear for normal/metal-rough),
  // then two neutral defaults: white and a flat (0,0,1) normal.
  auto uploadTexture = [&](uint32_t w, uint32_t h, const uint8_t* rgba, bool srgb) {
    WGPUTextureDescriptor td = {};
    td.usage = WGPUTextureUsage_TextureBinding | WGPUTextureUsage_CopyDst;
    td.dimension = WGPUTextureDimension_2D;
    td.size = { w, h, 1 };
    td.format = srgb ? WGPUTextureFormat_RGBA8UnormSrgb : WGPUTextureFormat_RGBA8Unorm;
    td.mipLevelCount = 1; td.sampleCount = 1;
    WGPUTexture tex = wgpuDeviceCreateTexture(device, &td);
    WGPUImageCopyTexture dst = {}; dst.texture = tex; dst.aspect = WGPUTextureAspect_All;
    WGPUTextureDataLayout layout = {}; layout.bytesPerRow = w * 4; layout.rowsPerImage = h;
    WGPUExtent3D ext = { w, h, 1 };
    wgpuQueueWriteTexture(queue, &dst, rgba, (size_t)w * h * 4, &layout, &ext);
    mesh.textures.push_back(tex);
    mesh.views.push_back(wgpuTextureCreateView(tex, nullptr));
    return (int)mesh.views.size() - 1;
  };
  for (const TextureData& t : data.textures)
    uploadTexture((uint32_t)t.width, (uint32_t)t.height, t.rgba.data(), t.srgb);
  const uint8_t white[4]      = { 255, 255, 255, 255 };
  const uint8_t flatNormal[4] = { 128, 128, 255, 255 };   // tangent-space (0,0,1)
  const int whiteIndex      = uploadTexture(1, 1, white, false);
  const int flatNormalIndex = uploadTexture(1, 1, flatNormal, false);

  // One bind group per submesh: uniform + its base/normal/metal-rough views (or defaults).
  for (const Submesh& sm : mesh.submeshes) {
    WGPUTextureView baseView   = mesh.views[sm.baseColor  >= 0 ? sm.baseColor  : whiteIndex];
    WGPUTextureView normalView = mesh.views[sm.normal     >= 0 ? sm.normal     : flatNormalIndex];
    WGPUTextureView mrView     = mesh.views[sm.metalRough >= 0 ? sm.metalRough : whiteIndex];
    WGPUBindGroupEntry bge[5] = {};
    bge[0].binding = 0; bge[0].buffer = mesh.uniformBuf; bge[0].size = sizeof(MeshUniforms);
    bge[1].binding = 1; bge[1].textureView = baseView;
    bge[2].binding = 2; bge[2].textureView = normalView;
    bge[3].binding = 3; bge[3].textureView = mrView;
    bge[4].binding = 4; bge[4].sampler = mesh.sampler;
    WGPUBindGroupDescriptor bgd = {};
    bgd.layout = bgl; bgd.entryCount = 5; bgd.entries = bge;
    mesh.bindGroups.push_back(wgpuDeviceCreateBindGroup(device, &bgd));
  }

  wgpuBindGroupLayoutRelease(bgl);
  return mesh;
}

// Ocean camera uniform (shared by the ocean surface).
struct OceanCamera {
  glm::mat4 viewProj;
  glm::vec4 eye;      // xyz camera position
  glm::vec4 params;   // x = time (s)
};

// FFT ocean surface: a large grid displaced/shaded by sampling the compute
// cascade's textures. Its bind group (which references per-frame ping-ponged
// textures) is rebuilt each frame, so only the layout + sampler are kept here.
struct Ocean {
  WGPURenderPipeline  pipeline;
  WGPUBuffer          vbuf, ibuf, uniformBuf;
  WGPUShaderModule    module;
  WGPUSampler         sampler;
  WGPUBindGroupLayout bgl;
  uint32_t            indexCount;
};

static Ocean createOcean(WGPUDevice device, WGPUQueue queue, WGPUTextureFormat colorFormat) {
  // Grid of XZ positions centred on the origin; the shader displaces + normals it.
  const int   N = 256;
  const float half = 300.0f;
  std::vector<float> gv;    gv.reserve((size_t)(N + 1) * (N + 1) * 2);
  std::vector<uint32_t> gi; gi.reserve((size_t)N * N * 6);
  for (int j = 0; j <= N; ++j)
    for (int i = 0; i <= N; ++i) {
      gv.push_back(-half + (float)i / N * 2.0f * half);
      gv.push_back(-half + (float)j / N * 2.0f * half);
    }
  for (int j = 0; j < N; ++j)
    for (int i = 0; i < N; ++i) {
      uint32_t a = (uint32_t)(j * (N + 1) + i), b = a + 1, c = a + (N + 1), d = c + 1;
      gi.insert(gi.end(), { a, c, b, b, c, d });
    }

  Ocean o;
  o.indexCount = (uint32_t)gi.size();

  WGPUBufferDescriptor vbd = {};
  vbd.usage = WGPUBufferUsage_Vertex | WGPUBufferUsage_CopyDst; vbd.size = gv.size() * sizeof(float);
  o.vbuf = wgpuDeviceCreateBuffer(device, &vbd);
  wgpuQueueWriteBuffer(queue, o.vbuf, 0, gv.data(), vbd.size);

  WGPUBufferDescriptor ibd = {};
  ibd.usage = WGPUBufferUsage_Index | WGPUBufferUsage_CopyDst; ibd.size = gi.size() * sizeof(uint32_t);
  o.ibuf = wgpuDeviceCreateBuffer(device, &ibd);
  wgpuQueueWriteBuffer(queue, o.ibuf, 0, gi.data(), ibd.size);

  WGPUBufferDescriptor ubd = {};
  ubd.usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst; ubd.size = sizeof(OceanCamera);
  o.uniformBuf = wgpuDeviceCreateBuffer(device, &ubd);

  WGPUShaderModuleWGSLDescriptor wgsl = {};
  wgsl.chain.sType = WGPUSType_ShaderModuleWGSLDescriptor;
  wgsl.code = OCEAN_SURFACE_WGSL;
  WGPUShaderModuleDescriptor smd = {};
  smd.nextInChain = &wgsl.chain;
  o.module = wgpuDeviceCreateShaderModule(device, &smd);

  // Linear, repeating sampler for the tiling FFT textures.
  WGPUSamplerDescriptor sd = {};
  sd.addressModeU = WGPUAddressMode_Repeat;
  sd.addressModeV = WGPUAddressMode_Repeat;
  sd.addressModeW = WGPUAddressMode_Repeat;
  sd.magFilter = WGPUFilterMode_Linear;
  sd.minFilter = WGPUFilterMode_Linear;
  sd.mipmapFilter = WGPUMipmapFilterMode_Nearest;
  sd.lodMinClamp = 0.0f; sd.lodMaxClamp = 1.0f; sd.maxAnisotropy = 1;
  o.sampler = wgpuDeviceCreateSampler(device, &sd);

  WGPUVertexAttribute attr = {};
  attr.format = WGPUVertexFormat_Float32x2; attr.offset = 0; attr.shaderLocation = 0;
  WGPUVertexBufferLayout vbl = {};
  vbl.arrayStride = 2 * sizeof(float);
  vbl.stepMode = WGPUVertexStepMode_Vertex;
  vbl.attributeCount = 1; vbl.attributes = &attr;

  WGPUDepthStencilState ds = {};
  ds.format = kDepthFormat;
  ds.depthWriteEnabled = true;
  ds.depthCompare = WGPUCompareFunction_Less;
  ds.stencilFront.compare = WGPUCompareFunction_Always;
  ds.stencilFront.failOp = WGPUStencilOperation_Keep;
  ds.stencilFront.depthFailOp = WGPUStencilOperation_Keep;
  ds.stencilFront.passOp = WGPUStencilOperation_Keep;
  ds.stencilBack = ds.stencilFront;
  ds.stencilReadMask = 0xFFFFFFFFu; ds.stencilWriteMask = 0xFFFFFFFFu;

  WGPUColorTargetState target = {};
  target.format = colorFormat; target.writeMask = WGPUColorWriteMask_All;
  WGPUFragmentState frag = {};
  frag.module = o.module; frag.entryPoint = "fs_main";
  frag.targetCount = 1; frag.targets = &target;

  WGPURenderPipelineDescriptor rpd = {};
  rpd.layout = nullptr;   // auto layout — inferred from the shader (uniform + 3 textures + sampler)
  rpd.vertex.module = o.module; rpd.vertex.entryPoint = "vs_main";
  rpd.vertex.bufferCount = 1; rpd.vertex.buffers = &vbl;
  rpd.primitive.topology = WGPUPrimitiveTopology_TriangleList;
  rpd.primitive.frontFace = WGPUFrontFace_CCW;
  rpd.primitive.cullMode = WGPUCullMode_None;
  rpd.depthStencil = &ds;
  rpd.multisample.count = 1; rpd.multisample.mask = 0xFFFFFFFFu;
  rpd.fragment = &frag;
  o.pipeline = wgpuDeviceCreateRenderPipeline(device, &rpd);
  o.bgl = wgpuRenderPipelineGetBindGroupLayout(o.pipeline, 0);
  return o;
}

static const char* backendTypeName(WGPUBackendType t) {
  switch (t) {
    case WGPUBackendType_D3D11:  return "D3D11";
    case WGPUBackendType_D3D12:  return "D3D12";
    case WGPUBackendType_Metal:  return "Metal";
    case WGPUBackendType_Vulkan: return "Vulkan";
    case WGPUBackendType_OpenGL: return "OpenGL";
    case WGPUBackendType_WebGPU: return "WebGPU";
    default:                     return "unknown";
  }
}

// Copy the just-rendered swapchain texture to the CPU and write a PNG (BGRA->RGBA).
static void captureSurface(WGPUDevice device, WGPUQueue queue, WGPUTexture tex,
                           uint32_t w, uint32_t h, const char* path) {
  const uint32_t rowBytes = ((w * 4) + 255u) & ~255u;   // 256-aligned for copyTextureToBuffer
  const size_t bufSize = (size_t)rowBytes * h;
  WGPUBufferDescriptor bd = {};
  bd.size = bufSize; bd.usage = WGPUBufferUsage_CopyDst | WGPUBufferUsage_MapRead;
  WGPUBuffer rb = wgpuDeviceCreateBuffer(device, &bd);

  WGPUCommandEncoder enc = wgpuDeviceCreateCommandEncoder(device, nullptr);
  WGPUImageCopyTexture src = {}; src.texture = tex; src.aspect = WGPUTextureAspect_All;
  WGPUImageCopyBuffer dst = {}; dst.buffer = rb; dst.layout.bytesPerRow = rowBytes; dst.layout.rowsPerImage = h;
  WGPUExtent3D ext = { w, h, 1 };
  wgpuCommandEncoderCopyTextureToBuffer(enc, &src, &dst, &ext);
  WGPUCommandBuffer cmd = wgpuCommandEncoderFinish(enc, nullptr);
  wgpuQueueSubmit(queue, 1, &cmd);
  wgpuCommandBufferRelease(cmd);
  wgpuCommandEncoderRelease(enc);

  struct St { bool done; } st{ false };
  wgpuBufferMapAsync(rb, WGPUMapMode_Read, 0, bufSize,
    [](WGPUBufferMapAsyncStatus, void* ud) { ((St*)ud)->done = true; }, &st);
  while (!st.done) {
#if defined(WEBGPU_BACKEND_WGPU)
    wgpuDevicePoll(device, true, nullptr);
#endif
  }
  const uint8_t* mapped = (const uint8_t*)wgpuBufferGetConstMappedRange(rb, 0, bufSize);
  std::vector<uint8_t> rgba((size_t)w * h * 4);
  for (uint32_t y = 0; y < h; ++y) {
    const uint8_t* srcRow = mapped + (size_t)y * rowBytes;
    uint8_t* dstRow = rgba.data() + (size_t)y * w * 4;
    for (uint32_t x = 0; x < w; ++x) {
      dstRow[x * 4 + 0] = srcRow[x * 4 + 2];   // R <- B
      dstRow[x * 4 + 1] = srcRow[x * 4 + 1];   // G
      dstRow[x * 4 + 2] = srcRow[x * 4 + 0];   // B <- R
      dstRow[x * 4 + 3] = srcRow[x * 4 + 3];   // A
    }
  }
  wgpuBufferUnmap(rb);
  wgpuBufferRelease(rb);
  int ok = stbi_write_png(path, (int)w, (int)h, 4, rgba.data(), (int)w * 4);
  std::printf("[spike] screenshot %s -> %s\n", ok ? "wrote" : "FAILED", path);
}

int main(int argc, char** argv) {
  // Flush per line so `[spike] …` progress shows even when piped or killed.
  std::setvbuf(stdout, nullptr, _IOLBF, 0);

  // Model to draw: argv[1] > $SAILSIM_MODEL > the ship (default) > rock > cube.
  const char* modelArg = (argc > 1) ? argv[1] : std::getenv("SAILSIM_MODEL");

  // Optional headless cap: render N frames then exit cleanly (for CI / smoke tests).
  const char* maxFramesEnv = std::getenv("SAILSIM_MAX_FRAMES");
  const long maxFrames = maxFramesEnv ? std::atol(maxFramesEnv) : 0;
  long frame = 0;

  // Headless screenshot: SAILSIM_SHOT=out.png renders to a chosen frame (default
  // 240, so the FFT/foam has settled), writes a PNG, and exits.
  const char* shotPath = std::getenv("SAILSIM_SHOT");
  const long shotFrame = shotPath ? (maxFramesEnv ? maxFrames : 240) : -1;

#if defined(WEBGPU_BACKEND_WGPU)
  // Surface wgpu-native's internal logs (including WGSL compile errors).
  wgpuSetLogLevel(WGPULogLevel_Warn);
  wgpuSetLogCallback([](WGPULogLevel level, char const* msg, void*) {
    std::fprintf(stderr, "[wgpu] (%d) %s\n", (int)level, msg ? msg : "");
  }, nullptr);
#endif

  // Headless compute-only mode: run the ocean-FFT readback test with no window,
  // then exit 0/1. Ideal for CI or a quick Windows/D3D12 check.
  if (std::getenv("SAILSIM_FFT_ONLY")) {
    WGPUInstanceDescriptor instDesc = {};
    WGPUInstance inst = wgpuCreateInstance(&instDesc);
    WGPURequestAdapterOptions ao = {};
    ao.powerPreference = WGPUPowerPreference_HighPerformance;
    WGPUAdapter ad = requestAdapterSync(inst, &ao);
    if (!ad) return EXIT_FAILURE;
    WGPUAdapterProperties props = {};
    wgpuAdapterGetProperties(ad, &props);
    std::printf("[spike] headless FFT test — backend=%s device=%s\n",
                backendTypeName(props.backendType), props.name ? props.name : "?");
    WGPUDeviceDescriptor dd = {};
    dd.label = "sailsim-device";
    WGPUDevice dev = requestDeviceSync(ad, &dd);
    if (!dev) return EXIT_FAILURE;
    wgpuDeviceSetUncapturedErrorCallback(dev, onDeviceError, nullptr);
    WGPUQueue q = wgpuDeviceGetQueue(dev);
    const bool ok = runInitialSpectrumTest(dev, q);
    wgpuQueueRelease(q);
    wgpuDeviceRelease(dev);
    wgpuAdapterRelease(ad);
    wgpuInstanceRelease(inst);
    return ok ? EXIT_SUCCESS : EXIT_FAILURE;
  }

  if (!glfwInit()) {
    std::fprintf(stderr, "[spike] glfwInit failed\n");
    return EXIT_FAILURE;
  }

  // WebGPU manages the drawing surface; tell GLFW not to create an OpenGL context.
  glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
  GLFWwindow* window = glfwCreateWindow(1280, 720, "sail-sim native — Phase 1: camera + depth", nullptr, nullptr);
  if (!window) {
    std::fprintf(stderr, "[spike] glfwCreateWindow failed\n");
    glfwTerminate();
    return EXIT_FAILURE;
  }

  // 1. Instance
  WGPUInstanceDescriptor instanceDesc = {};
  WGPUInstance instance = wgpuCreateInstance(&instanceDesc);
  if (!instance) {
    std::fprintf(stderr, "[spike] wgpuCreateInstance failed\n");
    return EXIT_FAILURE;
  }

  // 2. Surface (per-OS creation hidden inside glfw3webgpu)
  WGPUSurface surface = glfwGetWGPUSurface(instance, window);

  // 3. Adapter
  WGPURequestAdapterOptions adapterOpts = {};
  adapterOpts.compatibleSurface = surface;
  adapterOpts.powerPreference = WGPUPowerPreference_HighPerformance;
  WGPUAdapter adapter = requestAdapterSync(instance, &adapterOpts);
  if (!adapter) return EXIT_FAILURE;

  // Report which native backend was selected — the visible proof of the thesis.
  // wgpuAdapterGetProperties is present in both wgpu-native and Dawn 6512.
  WGPUAdapterProperties adapterProps = {};
  wgpuAdapterGetProperties(adapter, &adapterProps);
  std::printf("[spike] adapter: backend=%s  vendor=%s  device=%s\n",
              backendTypeName(adapterProps.backendType),
              adapterProps.vendorName ? adapterProps.vendorName : "?",
              adapterProps.name ? adapterProps.name : "?");

  // 4. Device + queue
  WGPUDeviceDescriptor deviceDesc = {};
  deviceDesc.label = "sailsim-device";
  WGPUDevice device = requestDeviceSync(adapter, &deviceDesc);
  if (!device) return EXIT_FAILURE;

  wgpuDeviceSetUncapturedErrorCallback(device, onDeviceError, nullptr);

  WGPUQueue queue = wgpuDeviceGetQueue(device);

  // Phase 0 criteria 3-5: prove the ocean-FFT WGSL runs natively and reads back.
  runInitialSpectrumTest(device, queue);

  // 5. Configure the surface (swapchain)
  WGPUSurfaceCapabilities caps = {};
  wgpuSurfaceGetCapabilities(surface, adapter, &caps);
  WGPUTextureFormat surfaceFormat = caps.formatCount > 0 ? caps.formats[0] : WGPUTextureFormat_BGRA8Unorm;

  int fbWidth = 0, fbHeight = 0;
  glfwGetFramebufferSize(window, &fbWidth, &fbHeight);

  WGPUSurfaceConfiguration surfaceConfig = {};
  surfaceConfig.device = device;
  surfaceConfig.format = surfaceFormat;
  surfaceConfig.usage = WGPUTextureUsage_RenderAttachment;
  surfaceConfig.width = (uint32_t)fbWidth;
  surfaceConfig.height = (uint32_t)fbHeight;
  surfaceConfig.presentMode = WGPUPresentMode_Fifo;   // vsync
  surfaceConfig.alphaMode = WGPUCompositeAlphaMode_Auto;
  if (shotPath) surfaceConfig.usage |= WGPUTextureUsage_CopySrc;   // allow screenshot readback
  wgpuSurfaceConfigure(surface, &surfaceConfig);

  std::printf("[spike] surface configured: %dx%d format=%d — entering render loop\n",
              fbWidth, fbHeight, (int)surfaceFormat);

  // Phase 1: load the model — explicit arg, else the ship, else the rock, else a cube.
  MeshData meshData;
  if (modelArg) {
    meshData = loadGltfMesh(modelArg);
  } else {
    meshData = loadGltfMesh(SAILSIM_SHIP_MODEL);                    // default: the merchantman
    if (!meshData.ok) meshData = loadGltfMesh(SAILSIM_ASSET_DIR "/rock_e.glb");
  }
  if (!meshData.ok) {
    std::printf("[spike] no model loaded — falling back to a cube\n");
    meshData = makeCubeMesh();
  }
  // Centre the model at the origin and scale it to a consistent on-screen size,
  // so any asset frames nicely regardless of its authored units.
  glm::vec3 bbMin(meshData.bbMin[0], meshData.bbMin[1], meshData.bbMin[2]);
  glm::vec3 bbMax(meshData.bbMax[0], meshData.bbMax[1], meshData.bbMax[2]);
  glm::vec3 center = 0.5f * (bbMin + bbMax);
  glm::vec3 extent = bbMax - bbMin;
  float maxExtent = std::max(extent.x, std::max(extent.y, extent.z));
  float fit = (maxExtent > 1e-6f) ? (2.0f / maxExtent) : 1.0f;
  const float shipScale = fit * 3.0f;
  // Place by the keel (X/Z centred, lowest point to y=0), not the bbox centre —
  // otherwise a tall-masted hull's centre sits up in the rigging and the hull
  // sinks. Draft is beam-based so it's robust to mast height.
  const glm::vec3 keelCenter(center.x, bbMin.y, center.z);
  const float draft = 0.22f * std::min(extent.x, extent.z) * shipScale;

  Mesh mesh = createMesh(device, queue, surfaceFormat, meshData);
  Ocean ocean = createOcean(device, queue, surfaceFormat);

  // FFT ocean — 3 cascades (250 / 17 / 5 m tiles) with split cutoff bands so they
  // don't double-count wavelengths. 256² each. Prime one frame + sanity-check.
  const float B1 = 6.2831853f / 17.0f * 6.0f;
  const float B2 = 6.2831853f / 5.0f  * 6.0f;
  OceanFFT c0(device, queue, 256, 250.0f, 0.0001f, B1);
  OceanFFT c1(device, queue, 256, 17.0f,  B1,      B2);
  OceanFFT c2(device, queue, 256, 5.0f,   B2,      9999.0f);
  for (OceanFFT* c : { &c0, &c1, &c2 }) { c->initSpectrum(); c->update(0.0f, 1.0f / 60.0f); }
  c0.sanityCheck();

  uint32_t curW = (uint32_t)fbWidth, curH = (uint32_t)fbHeight;
  WGPUTexture depthTex = makeDepthTexture(device, curW, curH);
  WGPUTextureView depthView = wgpuTextureCreateView(depthTex, nullptr);

  // 6. Render loop: draw the Gerstner ocean, then the ship floating on it.
  while (!glfwWindowShouldClose(window)) {
    glfwPollEvents();
    if (maxFrames > 0 && frame >= maxFrames) break;
    ++frame;

    // Handle window resize: reconfigure the surface and rebuild the depth buffer.
    int w = 0, h = 0;
    glfwGetFramebufferSize(window, &w, &h);
    if (w > 0 && h > 0 && ((uint32_t)w != curW || (uint32_t)h != curH)) {
      curW = (uint32_t)w; curH = (uint32_t)h;
      surfaceConfig.width = curW; surfaceConfig.height = curH;
      wgpuSurfaceConfigure(surface, &surfaceConfig);
      wgpuTextureViewRelease(depthView);
      wgpuTextureRelease(depthTex);
      depthTex = makeDepthTexture(device, curW, curH);
      depthView = wgpuTextureCreateView(depthTex, nullptr);
    }

    // Camera: slow orbit looking at the floating ship near the origin.
    float aspect = (float)curW / (float)curH;
    float t = (float)frame * (1.0f / 60.0f);
    float orbit = t * 0.08f;
    glm::vec3 eye(std::cos(orbit) * 7.0f, 3.2f, std::sin(orbit) * 7.0f);
    glm::mat4 viewM = glm::lookAt(eye, glm::vec3(0.0f, 0.3f, 0.0f), glm::vec3(0, 1, 0));
    glm::mat4 proj  = glm::perspective(glm::radians(50.0f), aspect, 0.1f, 2000.0f);
    glm::mat4 viewProj = proj * viewM;

    // Advance all cascades; uniform carries the three tile sizes.
    c0.update(t, 1.0f / 60.0f);
    c1.update(t, 1.0f / 60.0f);
    c2.update(t, 1.0f / 60.0f);
    OceanCamera oc{ viewProj, glm::vec4(eye, 1.0f),
                    glm::vec4(c0.lengthScale(), c1.lengthScale(), c2.lengthScale(), 0.0f) };
    wgpuQueueWriteBuffer(queue, ocean.uniformBuf, 0, &oc, sizeof(oc));

    // Float the ship on the wave field: heave to the surface height, tilt to the
    // surface normal (pitch + roll), plus a slow yaw. Sampled at the origin.
    float waveY = oceanHeight(0.0f, 0.0f, t);
    glm::vec3 up = oceanNormal(0.0f, 0.0f, t);
    glm::mat4 model = glm::translate(glm::mat4(1.0f), glm::vec3(0.0f, waveY - draft, 0.0f));
    glm::vec3 axis = glm::cross(glm::vec3(0, 1, 0), up);
    float axisLen = glm::length(axis);
    if (axisLen > 1e-5f) {
      float tiltAngle = std::asin(glm::clamp(axisLen, 0.0f, 1.0f));
      model = model * glm::rotate(glm::mat4(1.0f), tiltAngle, axis / axisLen);
    }
    model = glm::rotate(model, t * 0.05f, glm::vec3(0, 1, 0));   // slow yaw
    model = glm::scale(model, glm::vec3(shipScale));
    model = glm::translate(model, -keelCenter);                 // keel to origin
    MeshUniforms u{ viewProj * model, model, glm::vec4(eye, 1.0f) };
    wgpuQueueWriteBuffer(queue, mesh.uniformBuf, 0, &u, sizeof(u));

    WGPUSurfaceTexture surfaceTex;
    wgpuSurfaceGetCurrentTexture(surface, &surfaceTex);
    if (!surfaceTex.texture) continue;  // e.g. minimised / needs reconfigure

    WGPUTextureView view = wgpuTextureCreateView(surfaceTex.texture, nullptr);

    WGPUCommandEncoderDescriptor encDesc = {};
    WGPUCommandEncoder encoder = wgpuDeviceCreateCommandEncoder(device, &encDesc);

    WGPURenderPassColorAttachment colorAttachment = {};
    colorAttachment.view = view;
    colorAttachment.loadOp = WGPULoadOp_Clear;
    colorAttachment.storeOp = WGPUStoreOp_Store;
    colorAttachment.clearValue = WGPUColor{0.75, 0.85, 0.92, 1.0};   // sky
    // (Newer webgpu.h adds colorAttachment.depthSlice = WGPU_DEPTH_SLICE_UNDEFINED here;
    //  wgpu-native v0.19 has no such field — zero-init leaves it correctly unset.)

    WGPURenderPassDepthStencilAttachment depthAttachment = {};
    depthAttachment.view = depthView;
    depthAttachment.depthLoadOp = WGPULoadOp_Clear;
    depthAttachment.depthStoreOp = WGPUStoreOp_Store;
    depthAttachment.depthClearValue = 1.0f;

    WGPURenderPassDescriptor passDesc = {};
    passDesc.colorAttachmentCount = 1;
    passDesc.colorAttachments = &colorAttachment;
    passDesc.depthStencilAttachment = &depthAttachment;

    WGPURenderPassEncoder pass = wgpuCommandEncoderBeginRenderPass(encoder, &passDesc);
    // Ocean surface — bind group references this frame's (ping-ponged) cascade textures.
    WGPUBindGroupEntry oe[11] = {};
    oe[0].binding = 0;  oe[0].buffer = ocean.uniformBuf; oe[0].size = sizeof(OceanCamera);
    oe[1].binding = 1;  oe[1].textureView  = c0.displacement();
    oe[2].binding = 2;  oe[2].textureView  = c0.derivatives();
    oe[3].binding = 3;  oe[3].textureView  = c0.turbulence();
    oe[4].binding = 4;  oe[4].textureView  = c1.displacement();
    oe[5].binding = 5;  oe[5].textureView  = c1.derivatives();
    oe[6].binding = 6;  oe[6].textureView  = c1.turbulence();
    oe[7].binding = 7;  oe[7].textureView  = c2.displacement();
    oe[8].binding = 8;  oe[8].textureView  = c2.derivatives();
    oe[9].binding = 9;  oe[9].textureView  = c2.turbulence();
    oe[10].binding = 10; oe[10].sampler = ocean.sampler;
    WGPUBindGroupDescriptor obd = {};
    obd.layout = ocean.bgl; obd.entryCount = 11; obd.entries = oe;
    WGPUBindGroup oceanBG = wgpuDeviceCreateBindGroup(device, &obd);

    wgpuRenderPassEncoderSetPipeline(pass, ocean.pipeline);
    wgpuRenderPassEncoderSetBindGroup(pass, 0, oceanBG, 0, nullptr);
    wgpuRenderPassEncoderSetVertexBuffer(pass, 0, ocean.vbuf, 0, WGPU_WHOLE_SIZE);
    wgpuRenderPassEncoderSetIndexBuffer(pass, ocean.ibuf, WGPUIndexFormat_Uint32, 0, WGPU_WHOLE_SIZE);
    wgpuRenderPassEncoderDrawIndexed(pass, ocean.indexCount, 1, 0, 0, 0);

    // Ship.
    wgpuRenderPassEncoderSetPipeline(pass, mesh.pipeline);
    wgpuRenderPassEncoderSetVertexBuffer(pass, 0, mesh.vbuf, 0, WGPU_WHOLE_SIZE);
    wgpuRenderPassEncoderSetIndexBuffer(pass, mesh.ibuf, WGPUIndexFormat_Uint32, 0, WGPU_WHOLE_SIZE);
    for (size_t i = 0; i < mesh.submeshes.size(); ++i) {
      const Submesh& sm = mesh.submeshes[i];
      wgpuRenderPassEncoderSetBindGroup(pass, 0, mesh.bindGroups[i], 0, nullptr);
      wgpuRenderPassEncoderDrawIndexed(pass, sm.indexCount, 1, sm.indexOffset, 0, 0);
    }
    wgpuRenderPassEncoderEnd(pass);
    wgpuRenderPassEncoderRelease(pass);

    WGPUCommandBufferDescriptor cmdDesc = {};
    WGPUCommandBuffer cmd = wgpuCommandEncoderFinish(encoder, &cmdDesc);
    wgpuQueueSubmit(queue, 1, &cmd);

    if (shotPath && frame == shotFrame) {
      captureSurface(device, queue, surfaceTex.texture, curW, curH, shotPath);
      glfwSetWindowShouldClose(window, GLFW_TRUE);
    }

    wgpuCommandBufferRelease(cmd);
    wgpuCommandEncoderRelease(encoder);
    wgpuBindGroupRelease(oceanBG);
    wgpuTextureViewRelease(view);

#ifndef __EMSCRIPTEN__
    wgpuSurfacePresent(surface);
#endif

    // Let Dawn/wgpu service their internal work queues each frame.
#if defined(WEBGPU_BACKEND_DAWN)
    wgpuDeviceTick(device);
#elif defined(WEBGPU_BACKEND_WGPU)
    wgpuDevicePoll(device, false, nullptr);
#endif
  }

  std::printf("[spike] render loop exited after %ld frames — tearing down cleanly\n", frame);

  // 7. Teardown
  wgpuTextureViewRelease(depthView);
  wgpuTextureRelease(depthTex);
  wgpuRenderPipelineRelease(ocean.pipeline);
  wgpuSamplerRelease(ocean.sampler);
  wgpuBufferRelease(ocean.vbuf);
  wgpuBufferRelease(ocean.ibuf);
  wgpuBufferRelease(ocean.uniformBuf);
  wgpuShaderModuleRelease(ocean.module);
  wgpuRenderPipelineRelease(mesh.pipeline);
  for (WGPUBindGroup bg : mesh.bindGroups) wgpuBindGroupRelease(bg);
  for (WGPUTextureView v : mesh.views) wgpuTextureViewRelease(v);
  for (WGPUTexture t : mesh.textures) wgpuTextureRelease(t);
  wgpuSamplerRelease(mesh.sampler);
  wgpuBufferRelease(mesh.vbuf);
  wgpuBufferRelease(mesh.ibuf);
  wgpuBufferRelease(mesh.uniformBuf);
  wgpuShaderModuleRelease(mesh.module);
  wgpuQueueRelease(queue);
  wgpuDeviceRelease(device);
  wgpuAdapterRelease(adapter);
  wgpuSurfaceRelease(surface);
  wgpuInstanceRelease(instance);
  glfwDestroyWindow(window);
  glfwTerminate();
  return EXIT_SUCCESS;
}
