// sail-sim native client — Phase 0 spike: Dawn (WebGPU) device bringup + clear-colour loop.
//
// This is the smallest program that proves the PORTING.md thesis on real hardware:
// a Dawn-backed WebGPU device, running on D3D12 (Windows) or Metal (macOS), driving a
// swapchain. It prints the resolved backend so you can see D3D12/Metal/Vulkan at a glance.
//
// The WebGPU C API (webgpu.h) is version-sensitive. This file targets the "classic"
// callback style shipped by the eliemichel/WebGPU-distribution `dawn` branch, where
// requestAdapter/requestDevice resolve their callbacks synchronously. If your pinned
// header differs, the two request helpers below and the surface-status check are the
// only spots likely to need a one-line reconcile — see native/README.md.

#include <webgpu/webgpu.h>
#if defined(WEBGPU_BACKEND_WGPU)
#include <webgpu/wgpu.h>   // wgpu-native extensions (e.g. wgpuDevicePoll)
#endif
#include <glfw3webgpu.h>
#include <GLFW/glfw3.h>

#include <algorithm>
#include <cstdio>
#include <cstdlib>

#define GLM_FORCE_DEPTH_ZERO_TO_ONE   // WebGPU clip-space Z is [0,1], like D3D/Metal
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/constants.hpp>

#include <string>
#include <vector>
#include <map>
#include <future>
#include <chrono>
#include <thread>
#include <cstring>

#include "stb_image_write.h"

#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_wgpu.h"
#include "ui_font_body.h"    // generated by CMake: embedded body font (Inter)
#include "ui_font_title.h"   // generated by CMake: embedded title font (Cinzel)

#include "fft_test.hpp"
#include "gltf_mesh.hpp"
#include "net_auth.hpp"
#include "net_mp.hpp"
#include "ocean_fft.hpp"
#include "session.hpp"
#include "terrain.hpp"
#include "wave.hpp"
#include "mesh_wgsl.h"            // generated by CMake: inline const char* MESH_WGSL
#include "ocean_surface_wgsl.h"  // generated by CMake: inline const char* OCEAN_SURFACE_WGSL
#include "sky_wgsl.h"            // generated by CMake: inline const char* SKY_WGSL
#include "terrain_wgsl.h"        // generated by CMake: inline const char* TERRAIN_WGSL
#include "sea_far_wgsl.h"        // generated by CMake: inline const char* SEA_FAR_WGSL
#include "clouds_wgsl.h"         // generated by CMake: inline const char* CLOUDS_WGSL
#include "clouds_denoise_wgsl.h" // generated by CMake: inline const char* CLOUDS_DENOISE_WGSL

// ── async request helpers (resolve synchronously on Dawn/wgpu in this distribution) ──

static WGPUAdapter requestAdapterSync(WGPUInstance instance, const WGPURequestAdapterOptions* options) {
  struct Result { WGPUAdapter adapter = nullptr; bool done = false; } result;
  auto onAdapter = [](WGPURequestAdapterStatus status, WGPUAdapter adapter,
                      char const* message, void* userdata) {
    auto* r = static_cast<Result*>(userdata);
    if (status == WGPURequestAdapterStatus_Success) r->adapter = adapter;
    else std::fprintf(stderr, "[spike] requestAdapter failed: %s\n", message ? message : "(no message)");
    r->done = true;
  };
  wgpuInstanceRequestAdapter(instance, options, onAdapter, &result);
  // If a future header makes this genuinely async, pump events here instead of asserting.
  if (!result.done) std::fprintf(stderr, "[spike] requestAdapter did not resolve synchronously\n");
  return result.adapter;
}

static WGPUDevice requestDeviceSync(WGPUAdapter adapter, const WGPUDeviceDescriptor* descriptor) {
  struct Result { WGPUDevice device = nullptr; bool done = false; } result;
  auto onDevice = [](WGPURequestDeviceStatus status, WGPUDevice device,
                     char const* message, void* userdata) {
    auto* r = static_cast<Result*>(userdata);
    if (status == WGPURequestDeviceStatus_Success) r->device = device;
    else std::fprintf(stderr, "[spike] requestDevice failed: %s\n", message ? message : "(no message)");
    r->done = true;
  };
  wgpuAdapterRequestDevice(adapter, descriptor, onDevice, &result);
  if (!result.done) std::fprintf(stderr, "[spike] requestDevice did not resolve synchronously\n");
  return result.device;
}

static void onDeviceError(WGPUErrorType type, char const* message, void*) {
  std::fprintf(stderr, "[spike] uncaptured device error (%d): %s\n",
               (int)type, message ? message : "(no message)");
}

// Mouse-wheel accumulator (GLFW only delivers scroll via callback, not polling).
static double g_scrollAccum = 0.0;
static void onScroll(GLFWwindow*, double, double yoff) { g_scrollAccum += yoff; }

// Dark maritime ImGui theme: deep slate panels, teal accents, rounded corners.
static void styleSailSim() {
  ImGuiStyle& s = ImGui::GetStyle();
  s.WindowRounding = 8.0f; s.ChildRounding = 6.0f; s.FrameRounding = 5.0f;
  s.GrabRounding = 5.0f;   s.PopupRounding = 6.0f; s.ScrollbarRounding = 6.0f;
  s.WindowBorderSize = 1.0f; s.FrameBorderSize = 0.0f;
  s.WindowPadding = ImVec2(18, 16); s.FramePadding = ImVec2(12, 7);
  s.ItemSpacing = ImVec2(12, 11);   s.ItemInnerSpacing = ImVec2(8, 6);
  s.WindowTitleAlign = ImVec2(0.0f, 0.5f);

  const ImVec4 field   = ImVec4(0.12f, 0.15f, 0.19f, 1.00f);
  const ImVec4 accent  = ImVec4(0.15f, 0.55f, 0.62f, 1.00f);   // teal
  const ImVec4 accentH = ImVec4(0.20f, 0.68f, 0.76f, 1.00f);
  ImVec4* c = s.Colors;
  c[ImGuiCol_Text]            = ImVec4(0.86f, 0.90f, 0.93f, 1.00f);
  c[ImGuiCol_TextDisabled]    = ImVec4(0.45f, 0.50f, 0.55f, 1.00f);
  c[ImGuiCol_WindowBg]        = ImVec4(0.07f, 0.09f, 0.12f, 0.97f);
  c[ImGuiCol_PopupBg]         = ImVec4(0.07f, 0.09f, 0.12f, 0.98f);
  c[ImGuiCol_Border]          = ImVec4(0.20f, 0.26f, 0.32f, 0.70f);
  c[ImGuiCol_FrameBg]         = field;
  c[ImGuiCol_FrameBgHovered]  = ImVec4(0.16f, 0.20f, 0.25f, 1.00f);
  c[ImGuiCol_FrameBgActive]   = ImVec4(0.18f, 0.23f, 0.28f, 1.00f);
  c[ImGuiCol_TitleBg]         = ImVec4(0.09f, 0.12f, 0.15f, 1.00f);
  c[ImGuiCol_TitleBgActive]   = ImVec4(0.10f, 0.15f, 0.19f, 1.00f);
  c[ImGuiCol_Button]          = accent;
  c[ImGuiCol_ButtonHovered]   = accentH;
  c[ImGuiCol_ButtonActive]    = ImVec4(0.12f, 0.45f, 0.52f, 1.00f);
  c[ImGuiCol_CheckMark]       = accentH;
  c[ImGuiCol_Header]          = accent;
  c[ImGuiCol_HeaderHovered]   = accentH;
  c[ImGuiCol_HeaderActive]    = accent;
  c[ImGuiCol_Separator]       = ImVec4(0.20f, 0.26f, 0.32f, 0.70f);
}

static const WGPUTextureFormat kDepthFormat = WGPUTextureFormat_Depth24Plus;

// A framebuffer-sized depth texture, recreated on resize.
static WGPUTexture makeDepthTexture(WGPUDevice device, uint32_t w, uint32_t h) {
  WGPUTextureDescriptor td = {};
  td.usage = WGPUTextureUsage_RenderAttachment;
  td.dimension = WGPUTextureDimension_2D;
  td.size = { w, h, 1 };
  td.format = kDepthFormat;
  td.mipLevelCount = 1;
  td.sampleCount = 1;
  return wgpuDeviceCreateTexture(device, &td);
}

// Uniforms uploaded per frame: clip matrix, model matrix (for normals + world
// position), and the camera position (for the PBR view vector).
struct MeshUniforms {
  glm::mat4 mvp;
  glm::mat4 model;
  glm::vec4 eye;
};

// A depth-tested, PBR-shaded mesh (glTF-loaded or the fallback cube). Holds the
// pipeline, buffers, decoded textures, and one bind group per texture; draws as a
// sequence of submeshes, each selecting its material's base-colour texture.
// How many ships (you + remote players) one vessel mesh can draw per frame via
// dynamic uniform offsets. Each instance uses one aligned MeshUniforms slot.
static constexpr uint32_t kMaxShipInstances = 64;

struct Mesh {
  WGPURenderPipeline           pipeline;
  WGPUBuffer                   vbuf, ibuf, uniformBuf;
  WGPUShaderModule             module;
  WGPUSampler                  sampler;
  std::vector<WGPUTexture>     textures;     // decoded maps + 1x1 white + flat-normal defaults
  std::vector<WGPUTextureView> views;        // aligned with textures
  std::vector<WGPUBindGroup>   bindGroups;   // one per submesh
  std::vector<Submesh>         submeshes;
  uint32_t                     uniformStride = 0;   // bytes between per-ship uniform slots
  // Placement, computed at load from the model's bounds (see loadVessel).
  float     shipScale = 1.0f;
  float     draft = 0.0f;
  glm::vec3 keelCenter = glm::vec3(0.0f);
};

static Mesh createMesh(WGPUDevice device, WGPUQueue queue, WGPUTextureFormat colorFormat, const MeshData& data) {
  Mesh mesh;
  mesh.submeshes = data.submeshes;

  WGPUBufferDescriptor vbd = {};
  vbd.usage = WGPUBufferUsage_Vertex | WGPUBufferUsage_CopyDst;
  vbd.size = data.vertices.size() * sizeof(float);
  mesh.vbuf = wgpuDeviceCreateBuffer(device, &vbd);
  wgpuQueueWriteBuffer(queue, mesh.vbuf, 0, data.vertices.data(), vbd.size);

  WGPUBufferDescriptor ibd = {};
  ibd.usage = WGPUBufferUsage_Index | WGPUBufferUsage_CopyDst;
  ibd.size = data.indices.size() * sizeof(uint32_t);
  mesh.ibuf = wgpuDeviceCreateBuffer(device, &ibd);
  wgpuQueueWriteBuffer(queue, mesh.ibuf, 0, data.indices.data(), ibd.size);

  // One uniform slot per ship instance, at a 256-byte-aligned stride so each can be
  // selected by a dynamic bind-group offset (min offset alignment is 256).
  mesh.uniformStride = (uint32_t)((sizeof(MeshUniforms) + 255u) & ~size_t(255u));
  WGPUBufferDescriptor ubd = {};
  ubd.usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst;
  ubd.size = (uint64_t)mesh.uniformStride * kMaxShipInstances;
  mesh.uniformBuf = wgpuDeviceCreateBuffer(device, &ubd);

  WGPUShaderModuleWGSLDescriptor wgsl = {};
  wgsl.chain.sType = WGPUSType_ShaderModuleWGSLDescriptor;
  wgsl.code = MESH_WGSL;
  WGPUShaderModuleDescriptor smd = {};
  smd.nextInChain = &wgsl.chain;
  mesh.module = wgpuDeviceCreateShaderModule(device, &smd);

  // bind group layout: uniform (b0), base/normal/metal-rough textures (b1-3), sampler (b4)
  WGPUBindGroupLayoutEntry ble[5] = {};
  ble[0].binding = 0; ble[0].visibility = WGPUShaderStage_Vertex | WGPUShaderStage_Fragment;
  ble[0].buffer.type = WGPUBufferBindingType_Uniform;
  ble[0].buffer.hasDynamicOffset = true;   // select the per-ship slot at draw time
  for (int i = 1; i <= 3; ++i) {
    ble[i].binding = (uint32_t)i; ble[i].visibility = WGPUShaderStage_Fragment;
    ble[i].texture.sampleType = WGPUTextureSampleType_Float;
    ble[i].texture.viewDimension = WGPUTextureViewDimension_2D;
  }
  ble[4].binding = 4; ble[4].visibility = WGPUShaderStage_Fragment;
  ble[4].sampler.type = WGPUSamplerBindingType_Filtering;
  WGPUBindGroupLayoutDescriptor bgld = {};
  bgld.entryCount = 5; bgld.entries = ble;
  WGPUBindGroupLayout bgl = wgpuDeviceCreateBindGroupLayout(device, &bgld);

  WGPUPipelineLayoutDescriptor pld = {};
  pld.bindGroupLayoutCount = 1; pld.bindGroupLayouts = &bgl;
  WGPUPipelineLayout pl = wgpuDeviceCreatePipelineLayout(device, &pld);

  WGPUVertexAttribute attrs[5] = {};
  attrs[0].format = WGPUVertexFormat_Float32x3; attrs[0].offset = 0;                  attrs[0].shaderLocation = 0; // position
  attrs[1].format = WGPUVertexFormat_Float32x3; attrs[1].offset = 3  * sizeof(float); attrs[1].shaderLocation = 1; // normal
  attrs[2].format = WGPUVertexFormat_Float32x2; attrs[2].offset = 6  * sizeof(float); attrs[2].shaderLocation = 2; // uv
  attrs[3].format = WGPUVertexFormat_Float32x3; attrs[3].offset = 8  * sizeof(float); attrs[3].shaderLocation = 3; // albedo
  attrs[4].format = WGPUVertexFormat_Float32x2; attrs[4].offset = 11 * sizeof(float); attrs[4].shaderLocation = 4; // metallic, roughness
  WGPUVertexBufferLayout vbl = {};
  vbl.arrayStride = kFloatsPerVertex * sizeof(float);
  vbl.stepMode = WGPUVertexStepMode_Vertex;
  vbl.attributeCount = 5; vbl.attributes = attrs;

  WGPUDepthStencilState ds = {};
  ds.format = kDepthFormat;
  ds.depthWriteEnabled = true;
  ds.depthCompare = WGPUCompareFunction_Less;
  ds.stencilFront.compare = WGPUCompareFunction_Always;
  ds.stencilFront.failOp = WGPUStencilOperation_Keep;
  ds.stencilFront.depthFailOp = WGPUStencilOperation_Keep;
  ds.stencilFront.passOp = WGPUStencilOperation_Keep;
  ds.stencilBack = ds.stencilFront;
  ds.stencilReadMask = 0xFFFFFFFFu; ds.stencilWriteMask = 0xFFFFFFFFu;

  WGPUColorTargetState target = {};
  target.format = colorFormat;
  target.writeMask = WGPUColorWriteMask_All;
  WGPUFragmentState frag = {};
  frag.module = mesh.module; frag.entryPoint = "fs_main";
  frag.targetCount = 1; frag.targets = &target;

  WGPURenderPipelineDescriptor rpd = {};
  rpd.layout = pl;
  rpd.vertex.module = mesh.module;
  rpd.vertex.entryPoint = "vs_main";
  rpd.vertex.bufferCount = 1; rpd.vertex.buffers = &vbl;
  rpd.primitive.topology = WGPUPrimitiveTopology_TriangleList;
  rpd.primitive.frontFace = WGPUFrontFace_CCW;
  rpd.primitive.cullMode = WGPUCullMode_None;   // depth test handles occlusion
  rpd.depthStencil = &ds;
  rpd.multisample.count = 1;
  rpd.multisample.mask = 0xFFFFFFFFu;
  rpd.fragment = &frag;
  mesh.pipeline = wgpuDeviceCreateRenderPipeline(device, &rpd);
  wgpuPipelineLayoutRelease(pl);

  // linear, repeating sampler
  WGPUSamplerDescriptor sd = {};
  sd.addressModeU = WGPUAddressMode_Repeat;
  sd.addressModeV = WGPUAddressMode_Repeat;
  sd.addressModeW = WGPUAddressMode_Repeat;
  sd.magFilter = WGPUFilterMode_Linear;
  sd.minFilter = WGPUFilterMode_Linear;
  sd.mipmapFilter = WGPUMipmapFilterMode_Nearest;
  sd.lodMinClamp = 0.0f; sd.lodMaxClamp = 1.0f; sd.maxAnisotropy = 1;
  mesh.sampler = wgpuDeviceCreateSampler(device, &sd);

  // Upload decoded textures (sRGB for base colour, linear for normal/metal-rough),
  // then two neutral defaults: white and a flat (0,0,1) normal.
  auto uploadTexture = [&](uint32_t w, uint32_t h, const uint8_t* rgba, bool srgb) {
    WGPUTextureDescriptor td = {};
    td.usage = WGPUTextureUsage_TextureBinding | WGPUTextureUsage_CopyDst;
    td.dimension = WGPUTextureDimension_2D;
    td.size = { w, h, 1 };
    td.format = srgb ? WGPUTextureFormat_RGBA8UnormSrgb : WGPUTextureFormat_RGBA8Unorm;
    td.mipLevelCount = 1; td.sampleCount = 1;
    WGPUTexture tex = wgpuDeviceCreateTexture(device, &td);
    WGPUImageCopyTexture dst = {}; dst.texture = tex; dst.aspect = WGPUTextureAspect_All;
    WGPUTextureDataLayout layout = {}; layout.bytesPerRow = w * 4; layout.rowsPerImage = h;
    WGPUExtent3D ext = { w, h, 1 };
    wgpuQueueWriteTexture(queue, &dst, rgba, (size_t)w * h * 4, &layout, &ext);
    mesh.textures.push_back(tex);
    mesh.views.push_back(wgpuTextureCreateView(tex, nullptr));
    return (int)mesh.views.size() - 1;
  };
  for (const TextureData& t : data.textures)
    uploadTexture((uint32_t)t.width, (uint32_t)t.height, t.rgba.data(), t.srgb);
  const uint8_t white[4]      = { 255, 255, 255, 255 };
  const uint8_t flatNormal[4] = { 128, 128, 255, 255 };   // tangent-space (0,0,1)
  const int whiteIndex      = uploadTexture(1, 1, white, false);
  const int flatNormalIndex = uploadTexture(1, 1, flatNormal, false);

  // One bind group per submesh: uniform + its base/normal/metal-rough views (or defaults).
  for (const Submesh& sm : mesh.submeshes) {
    WGPUTextureView baseView   = mesh.views[sm.baseColor  >= 0 ? sm.baseColor  : whiteIndex];
    WGPUTextureView normalView = mesh.views[sm.normal     >= 0 ? sm.normal     : flatNormalIndex];
    WGPUTextureView mrView     = mesh.views[sm.metalRough >= 0 ? sm.metalRough : whiteIndex];
    WGPUBindGroupEntry bge[5] = {};
    bge[0].binding = 0; bge[0].buffer = mesh.uniformBuf; bge[0].size = sizeof(MeshUniforms);
    bge[1].binding = 1; bge[1].textureView = baseView;
    bge[2].binding = 2; bge[2].textureView = normalView;
    bge[3].binding = 3; bge[3].textureView = mrView;
    bge[4].binding = 4; bge[4].sampler = mesh.sampler;
    WGPUBindGroupDescriptor bgd = {};
    bgd.layout = bgl; bgd.entryCount = 5; bgd.entries = bge;
    mesh.bindGroups.push_back(wgpuDeviceCreateBindGroup(device, &bgd));
  }

  wgpuBindGroupLayoutRelease(bgl);
  return mesh;
}

// Load a vessel GLB and derive its on-water placement — a uniform scale to a
// consistent size, the keel origin (X/Z centred, lowest point to y=0), and a
// beam-based draught so the hull sits low in the water. Falls back to a cube.
static Mesh loadVessel(WGPUDevice device, WGPUQueue queue, WGPUTextureFormat fmt, const std::string& path) {
  MeshData data = loadGltfMesh(path.c_str());
  if (!data.ok) data = makeCubeMesh();
  glm::vec3 bbMin(data.bbMin[0], data.bbMin[1], data.bbMin[2]);
  glm::vec3 bbMax(data.bbMax[0], data.bbMax[1], data.bbMax[2]);
  glm::vec3 center = 0.5f * (bbMin + bbMax);
  glm::vec3 extent = bbMax - bbMin;
  float maxExtent = std::max(extent.x, std::max(extent.y, extent.z));
  float fit = (maxExtent > 1e-6f) ? (2.0f / maxExtent) : 1.0f;
  Mesh mesh = createMesh(device, queue, fmt, data);
  mesh.shipScale  = fit * 3.0f;
  mesh.keelCenter = glm::vec3(center.x, bbMin.y, center.z);
  mesh.draft      = 0.53f * std::min(extent.x, extent.z) * mesh.shipScale;   // see JS floatDraft
  return mesh;
}

// Vessel slug -> GLB path (mirrors server/controllers/vessels.controller.js). The
// ship GLBs sit beside the baked SAILSIM_SHIP_MODEL (…/server/assets/geometry/).
static std::string geometryDir() {
  std::string m = SAILSIM_SHIP_MODEL;
  size_t slash = m.find_last_of('/');
  return slash == std::string::npos ? std::string(".") : m.substr(0, slash);
}
static std::string glbForSlug(const std::string& slug) {
  std::string file =
      slug == "sloop"       ? "bermuda_sloop_rigged.glb" :
      slug == "brig"        ? "brig.glb" :
      slug == "merchantman" ? "merchantman.glb" :
      slug == "pinnace"     ? "pinnace.glb" :
                              "pinnace.glb";   // starter hull is the safe fallback
  return geometryDir() + "/" + file;
}

// Ocean camera uniform (shared by the ocean surface).
struct OceanCamera {
  glm::mat4 viewProj;
  glm::vec4 eye;      // xyz camera position
  glm::vec4 params;   // xyz = cascade tile sizes
  glm::vec4 screen;   // xy = framebuffer size (px)
};

// A colour render target (planar reflection).
static WGPUTexture makeColorRTT(WGPUDevice device, uint32_t w, uint32_t h, WGPUTextureFormat fmt) {
  WGPUTextureDescriptor td = {};
  td.usage = WGPUTextureUsage_RenderAttachment | WGPUTextureUsage_TextureBinding;
  td.dimension = WGPUTextureDimension_2D;
  td.size = { w, h, 1 };
  td.format = fmt;
  td.mipLevelCount = 1; td.sampleCount = 1;
  return wgpuDeviceCreateTexture(device, &td);
}

// FFT ocean surface: a large grid displaced/shaded by sampling the compute
// cascade's textures. Its bind group (which references per-frame ping-ponged
// textures) is rebuilt each frame, so only the layout + sampler are kept here.
struct Ocean {
  WGPURenderPipeline  pipeline;
  WGPUBuffer          vbuf, ibuf, uniformBuf;
  WGPUShaderModule    module;
  WGPUSampler         sampler;
  WGPUBindGroupLayout bgl;
  uint32_t            indexCount;
};

static Ocean createOcean(WGPUDevice device, WGPUQueue queue, WGPUTextureFormat colorFormat) {
  // Grid of XZ positions centred on the origin; the shader displaces + normals it.
  const int   N = 256;
  const float half = 300.0f;
  std::vector<float> gv;    gv.reserve((size_t)(N + 1) * (N + 1) * 2);
  std::vector<uint32_t> gi; gi.reserve((size_t)N * N * 6);
  for (int j = 0; j <= N; ++j)
    for (int i = 0; i <= N; ++i) {
      gv.push_back(-half + (float)i / N * 2.0f * half);
      gv.push_back(-half + (float)j / N * 2.0f * half);
    }
  for (int j = 0; j < N; ++j)
    for (int i = 0; i < N; ++i) {
      uint32_t a = (uint32_t)(j * (N + 1) + i), b = a + 1, c = a + (N + 1), d = c + 1;
      gi.insert(gi.end(), { a, c, b, b, c, d });
    }

  Ocean o;
  o.indexCount = (uint32_t)gi.size();

  WGPUBufferDescriptor vbd = {};
  vbd.usage = WGPUBufferUsage_Vertex | WGPUBufferUsage_CopyDst; vbd.size = gv.size() * sizeof(float);
  o.vbuf = wgpuDeviceCreateBuffer(device, &vbd);
  wgpuQueueWriteBuffer(queue, o.vbuf, 0, gv.data(), vbd.size);

  WGPUBufferDescriptor ibd = {};
  ibd.usage = WGPUBufferUsage_Index | WGPUBufferUsage_CopyDst; ibd.size = gi.size() * sizeof(uint32_t);
  o.ibuf = wgpuDeviceCreateBuffer(device, &ibd);
  wgpuQueueWriteBuffer(queue, o.ibuf, 0, gi.data(), ibd.size);

  WGPUBufferDescriptor ubd = {};
  ubd.usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst; ubd.size = sizeof(OceanCamera);
  o.uniformBuf = wgpuDeviceCreateBuffer(device, &ubd);

  WGPUShaderModuleWGSLDescriptor wgsl = {};
  wgsl.chain.sType = WGPUSType_ShaderModuleWGSLDescriptor;
  wgsl.code = OCEAN_SURFACE_WGSL;
  WGPUShaderModuleDescriptor smd = {};
  smd.nextInChain = &wgsl.chain;
  o.module = wgpuDeviceCreateShaderModule(device, &smd);

  // Linear, repeating sampler for the tiling FFT textures.
  WGPUSamplerDescriptor sd = {};
  sd.addressModeU = WGPUAddressMode_Repeat;
  sd.addressModeV = WGPUAddressMode_Repeat;
  sd.addressModeW = WGPUAddressMode_Repeat;
  sd.magFilter = WGPUFilterMode_Linear;
  sd.minFilter = WGPUFilterMode_Linear;
  sd.mipmapFilter = WGPUMipmapFilterMode_Nearest;
  sd.lodMinClamp = 0.0f; sd.lodMaxClamp = 1.0f; sd.maxAnisotropy = 1;
  o.sampler = wgpuDeviceCreateSampler(device, &sd);

  WGPUVertexAttribute attr = {};
  attr.format = WGPUVertexFormat_Float32x2; attr.offset = 0; attr.shaderLocation = 0;
  WGPUVertexBufferLayout vbl = {};
  vbl.arrayStride = 2 * sizeof(float);
  vbl.stepMode = WGPUVertexStepMode_Vertex;
  vbl.attributeCount = 1; vbl.attributes = &attr;

  WGPUDepthStencilState ds = {};
  ds.format = kDepthFormat;
  ds.depthWriteEnabled = true;
  ds.depthCompare = WGPUCompareFunction_Less;
  ds.stencilFront.compare = WGPUCompareFunction_Always;
  ds.stencilFront.failOp = WGPUStencilOperation_Keep;
  ds.stencilFront.depthFailOp = WGPUStencilOperation_Keep;
  ds.stencilFront.passOp = WGPUStencilOperation_Keep;
  ds.stencilBack = ds.stencilFront;
  ds.stencilReadMask = 0xFFFFFFFFu; ds.stencilWriteMask = 0xFFFFFFFFu;

  WGPUColorTargetState target = {};
  target.format = colorFormat; target.writeMask = WGPUColorWriteMask_All;
  WGPUFragmentState frag = {};
  frag.module = o.module; frag.entryPoint = "fs_main";
  frag.targetCount = 1; frag.targets = &target;

  // Explicit bind group layout (auto-layout misrouted binding 11): uniform (0),
  // 9 cascade textures (1-9), sampler (10), reflection (11). All float/filtering.
  WGPUBindGroupLayoutEntry be[12] = {};
  be[0].binding = 0; be[0].visibility = WGPUShaderStage_Vertex | WGPUShaderStage_Fragment;
  be[0].buffer.type = WGPUBufferBindingType_Uniform;
  for (int i = 1; i <= 9; ++i) {
    be[i].binding = (uint32_t)i; be[i].visibility = WGPUShaderStage_Vertex | WGPUShaderStage_Fragment;
    be[i].texture.sampleType = WGPUTextureSampleType_Float;
    be[i].texture.viewDimension = WGPUTextureViewDimension_2D;
  }
  be[10].binding = 10; be[10].visibility = WGPUShaderStage_Vertex | WGPUShaderStage_Fragment;
  be[10].sampler.type = WGPUSamplerBindingType_Filtering;
  be[11].binding = 11; be[11].visibility = WGPUShaderStage_Fragment;
  be[11].texture.sampleType = WGPUTextureSampleType_Float;
  be[11].texture.viewDimension = WGPUTextureViewDimension_2D;
  WGPUBindGroupLayoutDescriptor bld = {}; bld.entryCount = 12; bld.entries = be;
  o.bgl = wgpuDeviceCreateBindGroupLayout(device, &bld);
  WGPUPipelineLayoutDescriptor pld = {}; pld.bindGroupLayoutCount = 1; pld.bindGroupLayouts = &o.bgl;
  WGPUPipelineLayout pl = wgpuDeviceCreatePipelineLayout(device, &pld);

  WGPURenderPipelineDescriptor rpd = {};
  rpd.layout = pl;
  rpd.vertex.module = o.module; rpd.vertex.entryPoint = "vs_main";
  rpd.vertex.bufferCount = 1; rpd.vertex.buffers = &vbl;
  rpd.primitive.topology = WGPUPrimitiveTopology_TriangleList;
  rpd.primitive.frontFace = WGPUFrontFace_CCW;
  rpd.primitive.cullMode = WGPUCullMode_None;
  rpd.depthStencil = &ds;
  rpd.multisample.count = 1; rpd.multisample.mask = 0xFFFFFFFFu;
  rpd.fragment = &frag;
  o.pipeline = wgpuDeviceCreateRenderPipeline(device, &rpd);
  wgpuPipelineLayoutRelease(pl);
  return o;
}

// Procedural gradient sky drawn as a full-screen triangle (no vertex buffer).
struct SkyUniform { glm::mat4 invViewProj; glm::vec4 eye; glm::vec4 sun; };
struct Sky { WGPURenderPipeline pipeline; WGPUBuffer uniformBuf; WGPUBindGroup bindGroup; WGPUShaderModule module; };

static Sky createSky(WGPUDevice device, WGPUTextureFormat colorFormat) {
  Sky s;
  WGPUShaderModuleWGSLDescriptor wgsl = {};
  wgsl.chain.sType = WGPUSType_ShaderModuleWGSLDescriptor;
  wgsl.code = SKY_WGSL;
  WGPUShaderModuleDescriptor smd = {}; smd.nextInChain = &wgsl.chain;
  s.module = wgpuDeviceCreateShaderModule(device, &smd);

  WGPUDepthStencilState ds = {};
  ds.format = kDepthFormat;
  ds.depthWriteEnabled = false;              // background — don't occlude anything
  ds.depthCompare = WGPUCompareFunction_Always;
  ds.stencilFront.compare = WGPUCompareFunction_Always;
  ds.stencilFront.failOp = WGPUStencilOperation_Keep;
  ds.stencilFront.depthFailOp = WGPUStencilOperation_Keep;
  ds.stencilFront.passOp = WGPUStencilOperation_Keep;
  ds.stencilBack = ds.stencilFront;
  ds.stencilReadMask = 0xFFFFFFFFu; ds.stencilWriteMask = 0xFFFFFFFFu;

  WGPUColorTargetState target = {}; target.format = colorFormat; target.writeMask = WGPUColorWriteMask_All;
  WGPUFragmentState frag = {}; frag.module = s.module; frag.entryPoint = "fs_main"; frag.targetCount = 1; frag.targets = &target;

  WGPURenderPipelineDescriptor rpd = {};
  rpd.layout = nullptr;
  rpd.vertex.module = s.module; rpd.vertex.entryPoint = "vs_main";   // vertices generated in-shader
  rpd.primitive.topology = WGPUPrimitiveTopology_TriangleList;
  rpd.primitive.cullMode = WGPUCullMode_None;
  rpd.depthStencil = &ds;
  rpd.multisample.count = 1; rpd.multisample.mask = 0xFFFFFFFFu;
  rpd.fragment = &frag;
  s.pipeline = wgpuDeviceCreateRenderPipeline(device, &rpd);

  WGPUBufferDescriptor ubd = {};
  ubd.usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst; ubd.size = sizeof(SkyUniform);
  s.uniformBuf = wgpuDeviceCreateBuffer(device, &ubd);

  WGPUBindGroupLayout bgl = wgpuRenderPipelineGetBindGroupLayout(s.pipeline, 0);
  WGPUBindGroupEntry be = {}; be.binding = 0; be.buffer = s.uniformBuf; be.size = sizeof(SkyUniform);
  WGPUBindGroupDescriptor bgd = {}; bgd.layout = bgl; bgd.entryCount = 1; bgd.entries = &be;
  s.bindGroup = wgpuDeviceCreateBindGroup(device, &bgd);
  wgpuBindGroupLayoutRelease(bgl);
  return s;
}

static const char* backendTypeName(WGPUBackendType t) {
  switch (t) {
    case WGPUBackendType_D3D11:  return "D3D11";
    case WGPUBackendType_D3D12:  return "D3D12";
    case WGPUBackendType_Metal:  return "Metal";
    case WGPUBackendType_Vulkan: return "Vulkan";
    case WGPUBackendType_OpenGL: return "OpenGL";
    case WGPUBackendType_WebGPU: return "WebGPU";
    default:                     return "unknown";
  }
}

// Copy the just-rendered swapchain texture to the CPU and write a PNG (BGRA->RGBA).
static void captureSurface(WGPUDevice device, WGPUQueue queue, WGPUTexture tex,
                           uint32_t w, uint32_t h, const char* path) {
  const uint32_t rowBytes = ((w * 4) + 255u) & ~255u;   // 256-aligned for copyTextureToBuffer
  const size_t bufSize = (size_t)rowBytes * h;
  WGPUBufferDescriptor bd = {};
  bd.size = bufSize; bd.usage = WGPUBufferUsage_CopyDst | WGPUBufferUsage_MapRead;
  WGPUBuffer rb = wgpuDeviceCreateBuffer(device, &bd);

  WGPUCommandEncoder enc = wgpuDeviceCreateCommandEncoder(device, nullptr);
  WGPUImageCopyTexture src = {}; src.texture = tex; src.aspect = WGPUTextureAspect_All;
  WGPUImageCopyBuffer dst = {}; dst.buffer = rb; dst.layout.bytesPerRow = rowBytes; dst.layout.rowsPerImage = h;
  WGPUExtent3D ext = { w, h, 1 };
  wgpuCommandEncoderCopyTextureToBuffer(enc, &src, &dst, &ext);
  WGPUCommandBuffer cmd = wgpuCommandEncoderFinish(enc, nullptr);
  wgpuQueueSubmit(queue, 1, &cmd);
  wgpuCommandBufferRelease(cmd);
  wgpuCommandEncoderRelease(enc);

  struct St { bool done; } st{ false };
  wgpuBufferMapAsync(rb, WGPUMapMode_Read, 0, bufSize,
    [](WGPUBufferMapAsyncStatus, void* ud) { ((St*)ud)->done = true; }, &st);
  while (!st.done) {
#if defined(WEBGPU_BACKEND_WGPU)
    wgpuDevicePoll(device, true, nullptr);
#endif
  }
  const uint8_t* mapped = (const uint8_t*)wgpuBufferGetConstMappedRange(rb, 0, bufSize);
  std::vector<uint8_t> rgba((size_t)w * h * 4);
  for (uint32_t y = 0; y < h; ++y) {
    const uint8_t* srcRow = mapped + (size_t)y * rowBytes;
    uint8_t* dstRow = rgba.data() + (size_t)y * w * 4;
    for (uint32_t x = 0; x < w; ++x) {
      dstRow[x * 4 + 0] = srcRow[x * 4 + 2];   // R <- B
      dstRow[x * 4 + 1] = srcRow[x * 4 + 1];   // G
      dstRow[x * 4 + 2] = srcRow[x * 4 + 0];   // B <- R
      dstRow[x * 4 + 3] = srcRow[x * 4 + 3];   // A
    }
  }
  wgpuBufferUnmap(rb);
  wgpuBufferRelease(rb);
  int ok = stbi_write_png(path, (int)w, (int)h, 4, rgba.data(), (int)w * 4);
  std::printf("[spike] screenshot %s -> %s\n", ok ? "wrote" : "FAILED", path);
}

// ── Terrain rendering ─────────────────────────────────────────────────────────
struct TerrainU { glm::mat4 viewProj; glm::vec4 eye; glm::vec4 bounds; glm::vec4 misc; glm::vec4 sun; };
struct SeaFarU  { glm::mat4 viewProj; glm::vec4 eye; glm::vec4 sun; glm::vec4 origin; };

// A camera-following grid displaced by the world height texture. Pipeline/grid are
// built up front; the height texture + bind group are filled once terrain data
// arrives (uploadTerrainHeight), so rendering waits on the async fetch.
struct TerrainRender {
  WGPURenderPipeline pipeline; WGPUShaderModule module;
  WGPUBuffer vbuf, ibuf, uniformBuf; WGPUBindGroupLayout bgl;
  WGPUTexture heightTex = nullptr; WGPUTextureView heightView = nullptr;
  WGPUBindGroup bindGroup = nullptr;
  uint32_t indexCount = 0; bool ready = false;
};

static WGPUShaderModule makeWGSL(WGPUDevice device, const char* code) {
  WGPUShaderModuleWGSLDescriptor wgsl = {};
  wgsl.chain.sType = WGPUSType_ShaderModuleWGSLDescriptor;
  wgsl.code = code;
  WGPUShaderModuleDescriptor smd = {};
  smd.nextInChain = &wgsl.chain;
  return wgpuDeviceCreateShaderModule(device, &smd);
}

// Grid of XZ positions spanning [-half, half]; the shader recentres it on the ship.
static void makeXZGrid(int N, float half, std::vector<float>& v, std::vector<uint32_t>& idx) {
  v.reserve((size_t)(N + 1) * (N + 1) * 2);
  for (int j = 0; j <= N; ++j)
    for (int i = 0; i <= N; ++i) {
      v.push_back(-half + (float)i / N * 2.0f * half);
      v.push_back(-half + (float)j / N * 2.0f * half);
    }
  idx.reserve((size_t)N * N * 6);
  for (int j = 0; j < N; ++j)
    for (int i = 0; i < N; ++i) {
      uint32_t a = (uint32_t)(j * (N + 1) + i), b = a + 1, c = a + (N + 1), d = c + 1;
      idx.insert(idx.end(), { a, c, b, b, c, d });
    }
}

static TerrainRender createTerrainRender(WGPUDevice device, WGPUQueue queue, WGPUTextureFormat colorFormat) {
  TerrainRender t;
  std::vector<float> v; std::vector<uint32_t> idx;
  makeXZGrid(512, 4000.0f, v, idx);   // +/-4 km around the ship, ~15.6 m cells
  t.indexCount = (uint32_t)idx.size();

  WGPUBufferDescriptor vbd = {}; vbd.usage = WGPUBufferUsage_Vertex | WGPUBufferUsage_CopyDst;
  vbd.size = v.size() * sizeof(float); t.vbuf = wgpuDeviceCreateBuffer(device, &vbd);
  wgpuQueueWriteBuffer(queue, t.vbuf, 0, v.data(), vbd.size);
  WGPUBufferDescriptor ibd = {}; ibd.usage = WGPUBufferUsage_Index | WGPUBufferUsage_CopyDst;
  ibd.size = idx.size() * sizeof(uint32_t); t.ibuf = wgpuDeviceCreateBuffer(device, &ibd);
  wgpuQueueWriteBuffer(queue, t.ibuf, 0, idx.data(), ibd.size);
  WGPUBufferDescriptor ubd = {}; ubd.usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst;
  ubd.size = sizeof(TerrainU); t.uniformBuf = wgpuDeviceCreateBuffer(device, &ubd);

  t.module = makeWGSL(device, TERRAIN_WGSL);

  WGPUBindGroupLayoutEntry ble[2] = {};
  ble[0].binding = 0; ble[0].visibility = WGPUShaderStage_Vertex | WGPUShaderStage_Fragment;
  ble[0].buffer.type = WGPUBufferBindingType_Uniform;
  ble[1].binding = 1; ble[1].visibility = WGPUShaderStage_Vertex | WGPUShaderStage_Fragment;
  ble[1].texture.sampleType = WGPUTextureSampleType_UnfilterableFloat;   // R32F
  ble[1].texture.viewDimension = WGPUTextureViewDimension_2D;
  WGPUBindGroupLayoutDescriptor bgld = {}; bgld.entryCount = 2; bgld.entries = ble;
  t.bgl = wgpuDeviceCreateBindGroupLayout(device, &bgld);
  WGPUPipelineLayoutDescriptor pld = {}; pld.bindGroupLayoutCount = 1; pld.bindGroupLayouts = &t.bgl;
  WGPUPipelineLayout pl = wgpuDeviceCreatePipelineLayout(device, &pld);

  WGPUVertexAttribute attr = {}; attr.format = WGPUVertexFormat_Float32x2; attr.offset = 0; attr.shaderLocation = 0;
  WGPUVertexBufferLayout vbl = {}; vbl.arrayStride = 2 * sizeof(float); vbl.attributeCount = 1; vbl.attributes = &attr;
  WGPUDepthStencilState ds = {}; ds.format = kDepthFormat; ds.depthWriteEnabled = true; ds.depthCompare = WGPUCompareFunction_Less;
  ds.stencilFront.compare = WGPUCompareFunction_Always; ds.stencilBack.compare = WGPUCompareFunction_Always;
  ds.stencilReadMask = 0xFFFFFFFFu; ds.stencilWriteMask = 0xFFFFFFFFu;
  WGPUColorTargetState target = {}; target.format = colorFormat; target.writeMask = WGPUColorWriteMask_All;
  WGPUFragmentState frag = {}; frag.module = t.module; frag.entryPoint = "fs_main"; frag.targetCount = 1; frag.targets = &target;
  WGPURenderPipelineDescriptor rpd = {}; rpd.layout = pl;
  rpd.vertex.module = t.module; rpd.vertex.entryPoint = "vs_main"; rpd.vertex.bufferCount = 1; rpd.vertex.buffers = &vbl;
  rpd.primitive.topology = WGPUPrimitiveTopology_TriangleList; rpd.primitive.frontFace = WGPUFrontFace_CCW; rpd.primitive.cullMode = WGPUCullMode_None;
  rpd.depthStencil = &ds; rpd.multisample.count = 1; rpd.multisample.mask = 0xFFFFFFFFu; rpd.fragment = &frag;
  t.pipeline = wgpuDeviceCreateRenderPipeline(device, &rpd);
  wgpuPipelineLayoutRelease(pl);
  return t;
}

static void uploadTerrainHeight(WGPUDevice device, WGPUQueue queue, TerrainRender& t,
                                int W, int H, const float* data) {
  WGPUTextureDescriptor td = {};
  td.usage = WGPUTextureUsage_TextureBinding | WGPUTextureUsage_CopyDst;
  td.dimension = WGPUTextureDimension_2D; td.size = { (uint32_t)W, (uint32_t)H, 1 };
  td.format = WGPUTextureFormat_R32Float; td.mipLevelCount = 1; td.sampleCount = 1;
  t.heightTex = wgpuDeviceCreateTexture(device, &td);
  WGPUImageCopyTexture dst = {}; dst.texture = t.heightTex; dst.aspect = WGPUTextureAspect_All;
  WGPUTextureDataLayout dl = {}; dl.bytesPerRow = (uint32_t)W * 4; dl.rowsPerImage = (uint32_t)H;
  WGPUExtent3D ext = { (uint32_t)W, (uint32_t)H, 1 };
  wgpuQueueWriteTexture(queue, &dst, data, (size_t)W * H * 4, &dl, &ext);
  t.heightView = wgpuTextureCreateView(t.heightTex, nullptr);

  WGPUBindGroupEntry bge[2] = {};
  bge[0].binding = 0; bge[0].buffer = t.uniformBuf; bge[0].size = sizeof(TerrainU);
  bge[1].binding = 1; bge[1].textureView = t.heightView;
  WGPUBindGroupDescriptor bgd = {}; bgd.layout = t.bgl; bgd.entryCount = 2; bgd.entries = bge;
  t.bindGroup = wgpuDeviceCreateBindGroup(device, &bgd);
  t.ready = true;
}

struct SeaFar { WGPURenderPipeline pipeline; WGPUShaderModule module; WGPUBuffer vbuf, uniformBuf; WGPUBindGroup bindGroup; };

static SeaFar createSeaFar(WGPUDevice device, WGPUQueue queue, WGPUTextureFormat colorFormat) {
  SeaFar s;
  const float B = 26000.0f;   // covers the +/-25 km world with margin
  const float verts[12] = { -B, -B,  B, -B,  B, B,  -B, -B,  B, B,  -B, B };
  WGPUBufferDescriptor vbd = {}; vbd.usage = WGPUBufferUsage_Vertex | WGPUBufferUsage_CopyDst; vbd.size = sizeof(verts);
  s.vbuf = wgpuDeviceCreateBuffer(device, &vbd); wgpuQueueWriteBuffer(queue, s.vbuf, 0, verts, sizeof(verts));
  WGPUBufferDescriptor ubd = {}; ubd.usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst; ubd.size = sizeof(SeaFarU);
  s.uniformBuf = wgpuDeviceCreateBuffer(device, &ubd);
  s.module = makeWGSL(device, SEA_FAR_WGSL);

  WGPUBindGroupLayoutEntry ble = {}; ble.binding = 0; ble.visibility = WGPUShaderStage_Vertex | WGPUShaderStage_Fragment;
  ble.buffer.type = WGPUBufferBindingType_Uniform;
  WGPUBindGroupLayoutDescriptor bgld = {}; bgld.entryCount = 1; bgld.entries = &ble;
  WGPUBindGroupLayout bgl = wgpuDeviceCreateBindGroupLayout(device, &bgld);
  WGPUPipelineLayoutDescriptor pld = {}; pld.bindGroupLayoutCount = 1; pld.bindGroupLayouts = &bgl;
  WGPUPipelineLayout pl = wgpuDeviceCreatePipelineLayout(device, &pld);

  WGPUVertexAttribute attr = {}; attr.format = WGPUVertexFormat_Float32x2; attr.shaderLocation = 0;
  WGPUVertexBufferLayout vbl = {}; vbl.arrayStride = 2 * sizeof(float); vbl.attributeCount = 1; vbl.attributes = &attr;
  WGPUDepthStencilState ds = {}; ds.format = kDepthFormat; ds.depthWriteEnabled = true; ds.depthCompare = WGPUCompareFunction_Less;
  ds.stencilFront.compare = WGPUCompareFunction_Always; ds.stencilBack.compare = WGPUCompareFunction_Always;
  ds.stencilReadMask = 0xFFFFFFFFu; ds.stencilWriteMask = 0xFFFFFFFFu;
  WGPUColorTargetState target = {}; target.format = colorFormat; target.writeMask = WGPUColorWriteMask_All;
  WGPUFragmentState frag = {}; frag.module = s.module; frag.entryPoint = "fs_main"; frag.targetCount = 1; frag.targets = &target;
  WGPURenderPipelineDescriptor rpd = {}; rpd.layout = pl;
  rpd.vertex.module = s.module; rpd.vertex.entryPoint = "vs_main"; rpd.vertex.bufferCount = 1; rpd.vertex.buffers = &vbl;
  rpd.primitive.topology = WGPUPrimitiveTopology_TriangleList; rpd.primitive.cullMode = WGPUCullMode_None;
  rpd.depthStencil = &ds; rpd.multisample.count = 1; rpd.multisample.mask = 0xFFFFFFFFu; rpd.fragment = &frag;
  s.pipeline = wgpuDeviceCreateRenderPipeline(device, &rpd);
  wgpuPipelineLayoutRelease(pl);

  WGPUBindGroupEntry bge = {}; bge.binding = 0; bge.buffer = s.uniformBuf; bge.size = sizeof(SeaFarU);
  WGPUBindGroupDescriptor bgd = {}; bgd.layout = bgl; bgd.entryCount = 1; bgd.entries = &bge;
  s.bindGroup = wgpuDeviceCreateBindGroup(device, &bgd);
  wgpuBindGroupLayoutRelease(bgl);
  return s;
}

// ── Volumetric clouds ─────────────────────────────────────────────────────────
struct CloudU {
  glm::mat4 invViewProj; glm::vec4 camPos; glm::vec4 sunDir;
  glm::vec4 sunCol; glm::vec4 skyCol; glm::vec4 groundCol;
  glm::vec4 slab;   // cloudBase, cloudTop, coverage, type
  glm::vec4 anim;   // time, driftX, driftZ, farZ
};
struct Clouds {
  WGPURenderPipeline pipeline; WGPUShaderModule module; WGPUBuffer uniformBuf;
  WGPUTexture noiseTex, weatherTex; WGPUTextureView noiseView, weatherView;
  WGPUSampler noiseSamp, weatherSamp; WGPUBindGroup bindGroup;
  // Denoise: the cloud march writes an offscreen RGBA16F buffer that this 5x5
  // bilateral pass filters and composites over the scene.
  WGPURenderPipeline denoisePipeline; WGPUShaderModule denoiseModule;
  WGPUBindGroupLayout denoiseBGL; WGPUBuffer denoiseUniform; WGPUSampler cloudSamp;
};
static const WGPUTextureFormat kCloudFormat = WGPUTextureFormat_RGBA16Float;

// Tiling value noise (the client bakes an equivalent 3-D noise atlas + weather map).
static float cn_lattice(int x, int y, int z, int P) {
  x = ((x % P) + P) % P; y = ((y % P) + P) % P; z = ((z % P) + P) % P;
  uint32_t n = (uint32_t)(x * 73856093) ^ (uint32_t)(y * 19349663) ^ (uint32_t)(z * 83492791);
  n = (n << 13) ^ n;
  n = n * (n * n * 15731u + 789221u) + 1376312589u;
  return (float)(n & 0x7fffffffu) / (float)0x7fffffff;
}
static float cn_smooth(float t) { return t * t * (3.0f - 2.0f * t); }
static float cn_lerp(float a, float b, float t) { return a + (b - a) * t; }
static float cn_valueNoise3(float fx, float fy, float fz, int P) {
  float ux = fx * P, uy = fy * P, uz = fz * P;
  int ix = (int)std::floor(ux), iy = (int)std::floor(uy), iz = (int)std::floor(uz);
  float tx = cn_smooth(ux - ix), ty = cn_smooth(uy - iy), tz = cn_smooth(uz - iz);
  auto L = [&](int dx, int dy, int dz) { return cn_lattice(ix + dx, iy + dy, iz + dz, P); };
  float c00 = cn_lerp(L(0,0,0), L(1,0,0), tx), c10 = cn_lerp(L(0,1,0), L(1,1,0), tx);
  float c01 = cn_lerp(L(0,0,1), L(1,0,1), tx), c11 = cn_lerp(L(0,1,1), L(1,1,1), tx);
  return cn_lerp(cn_lerp(c00, c10, ty), cn_lerp(c01, c11, ty), tz);
}

static Clouds createClouds(WGPUDevice device, WGPUQueue queue, WGPUTextureFormat colorFormat) {
  Clouds c;
  // 3-D noise atlas: 32^3 tiling value noise packed 8x4 into 256x128 R8.
  std::vector<uint8_t> atlas((size_t)256 * 128, 0);
  for (int z = 0; z < 32; ++z) {
    int col = z % 8, row = z / 8;
    for (int y = 0; y < 32; ++y)
      for (int x = 0; x < 32; ++x) {
        float f = 0.55f * cn_valueNoise3(x / 32.0f, y / 32.0f, z / 32.0f, 4)
                + 0.30f * cn_valueNoise3(x / 32.0f, y / 32.0f, z / 32.0f, 8)
                + 0.15f * cn_valueNoise3(x / 32.0f, y / 32.0f, z / 32.0f, 16);
        atlas[(size_t)(row * 32 + y) * 256 + (col * 32 + x)] = (uint8_t)(glm::clamp(f, 0.0f, 1.0f) * 255.0f);
      }
  }
  // Weather map: 256^2 tiling FBM (use z=0 slice of the value noise across octaves).
  std::vector<uint8_t> weather((size_t)256 * 256, 0);
  for (int y = 0; y < 256; ++y)
    for (int x = 0; x < 256; ++x) {
      float fx = x / 256.0f, fy = y / 256.0f, w = 0.0f, amp = 0.5f; int P = 3;
      for (int o = 0; o < 5; ++o) { w += amp * cn_valueNoise3(fx, fy, 0.37f, P); amp *= 0.5f; P *= 2; }
      weather[(size_t)y * 256 + x] = (uint8_t)(glm::clamp(w, 0.0f, 1.0f) * 255.0f);
    }

  auto makeR8 = [&](int w, int h, const uint8_t* data) {
    WGPUTextureDescriptor td = {}; td.usage = WGPUTextureUsage_TextureBinding | WGPUTextureUsage_CopyDst;
    td.dimension = WGPUTextureDimension_2D; td.size = { (uint32_t)w, (uint32_t)h, 1 };
    td.format = WGPUTextureFormat_R8Unorm; td.mipLevelCount = 1; td.sampleCount = 1;
    WGPUTexture tex = wgpuDeviceCreateTexture(device, &td);
    WGPUImageCopyTexture dst = {}; dst.texture = tex; dst.aspect = WGPUTextureAspect_All;
    WGPUTextureDataLayout dl = {}; dl.bytesPerRow = (uint32_t)w; dl.rowsPerImage = (uint32_t)h;
    WGPUExtent3D ext = { (uint32_t)w, (uint32_t)h, 1 };
    wgpuQueueWriteTexture(queue, &dst, data, (size_t)w * h, &dl, &ext);
    return tex;
  };
  c.noiseTex   = makeR8(256, 128, atlas.data());
  c.weatherTex = makeR8(256, 256, weather.data());
  c.noiseView   = wgpuTextureCreateView(c.noiseTex, nullptr);
  c.weatherView = wgpuTextureCreateView(c.weatherTex, nullptr);

  auto makeSampler = [&](WGPUAddressMode mode) {
    WGPUSamplerDescriptor sd = {}; sd.addressModeU = mode; sd.addressModeV = mode; sd.addressModeW = mode;
    sd.magFilter = WGPUFilterMode_Linear; sd.minFilter = WGPUFilterMode_Linear; sd.mipmapFilter = WGPUMipmapFilterMode_Nearest;
    sd.lodMinClamp = 0.0f; sd.lodMaxClamp = 1.0f; sd.maxAnisotropy = 1;
    return wgpuDeviceCreateSampler(device, &sd);
  };
  c.noiseSamp   = makeSampler(WGPUAddressMode_ClampToEdge);
  c.weatherSamp = makeSampler(WGPUAddressMode_MirrorRepeat);

  WGPUBufferDescriptor ubd = {}; ubd.usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst; ubd.size = sizeof(CloudU);
  c.uniformBuf = wgpuDeviceCreateBuffer(device, &ubd);
  c.module = makeWGSL(device, CLOUDS_WGSL);

  WGPUBindGroupLayoutEntry ble[5] = {};
  ble[0].binding = 0; ble[0].visibility = WGPUShaderStage_Fragment; ble[0].buffer.type = WGPUBufferBindingType_Uniform;
  ble[1].binding = 1; ble[1].visibility = WGPUShaderStage_Fragment; ble[1].texture.sampleType = WGPUTextureSampleType_Float; ble[1].texture.viewDimension = WGPUTextureViewDimension_2D;
  ble[2].binding = 2; ble[2].visibility = WGPUShaderStage_Fragment; ble[2].sampler.type = WGPUSamplerBindingType_Filtering;
  ble[3].binding = 3; ble[3].visibility = WGPUShaderStage_Fragment; ble[3].texture.sampleType = WGPUTextureSampleType_Float; ble[3].texture.viewDimension = WGPUTextureViewDimension_2D;
  ble[4].binding = 4; ble[4].visibility = WGPUShaderStage_Fragment; ble[4].sampler.type = WGPUSamplerBindingType_Filtering;
  WGPUBindGroupLayoutDescriptor bgld = {}; bgld.entryCount = 5; bgld.entries = ble;
  WGPUBindGroupLayout bgl = wgpuDeviceCreateBindGroupLayout(device, &bgld);
  WGPUPipelineLayoutDescriptor pld = {}; pld.bindGroupLayoutCount = 1; pld.bindGroupLayouts = &bgl;
  WGPUPipelineLayout pl = wgpuDeviceCreatePipelineLayout(device, &pld);

  // March writes the offscreen RGBA16F cloud buffer (no blend — cleared to 0, the
  // depth test lets geometry occlude); depth-test (no write) against the scene.
  WGPUColorTargetState target = {}; target.format = kCloudFormat; target.writeMask = WGPUColorWriteMask_All;
  WGPUDepthStencilState ds = {}; ds.format = kDepthFormat; ds.depthWriteEnabled = false; ds.depthCompare = WGPUCompareFunction_LessEqual;
  ds.stencilFront.compare = WGPUCompareFunction_Always; ds.stencilBack.compare = WGPUCompareFunction_Always;
  ds.stencilReadMask = 0xFFFFFFFFu; ds.stencilWriteMask = 0xFFFFFFFFu;
  WGPUFragmentState frag = {}; frag.module = c.module; frag.entryPoint = "fs_main"; frag.targetCount = 1; frag.targets = &target;
  WGPURenderPipelineDescriptor rpd = {}; rpd.layout = pl;
  rpd.vertex.module = c.module; rpd.vertex.entryPoint = "vs_main";
  rpd.primitive.topology = WGPUPrimitiveTopology_TriangleList;
  rpd.depthStencil = &ds; rpd.multisample.count = 1; rpd.multisample.mask = 0xFFFFFFFFu; rpd.fragment = &frag;
  c.pipeline = wgpuDeviceCreateRenderPipeline(device, &rpd);
  wgpuPipelineLayoutRelease(pl);

  WGPUBindGroupEntry bge[5] = {};
  bge[0].binding = 0; bge[0].buffer = c.uniformBuf; bge[0].size = sizeof(CloudU);
  bge[1].binding = 1; bge[1].textureView = c.noiseView;
  bge[2].binding = 2; bge[2].sampler = c.noiseSamp;
  bge[3].binding = 3; bge[3].textureView = c.weatherView;
  bge[4].binding = 4; bge[4].sampler = c.weatherSamp;
  WGPUBindGroupDescriptor bgd = {}; bgd.layout = bgl; bgd.entryCount = 5; bgd.entries = bge;
  c.bindGroup = wgpuDeviceCreateBindGroup(device, &bgd);
  wgpuBindGroupLayoutRelease(bgl);

  // ── Denoise / composite pipeline: 5x5 bilateral over the cloud buffer, blended
  //    (premultiplied) onto the swapchain. Its bind group (which references the
  //    resizable cloud buffer) is rebuilt in the render loop. ──
  c.cloudSamp = makeSampler(WGPUAddressMode_ClampToEdge);
  WGPUBufferDescriptor dud = {}; dud.usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst; dud.size = 16;
  c.denoiseUniform = wgpuDeviceCreateBuffer(device, &dud);
  c.denoiseModule = makeWGSL(device, CLOUDS_DENOISE_WGSL);

  WGPUBindGroupLayoutEntry dble[3] = {};
  dble[0].binding = 0; dble[0].visibility = WGPUShaderStage_Fragment; dble[0].buffer.type = WGPUBufferBindingType_Uniform;
  dble[1].binding = 1; dble[1].visibility = WGPUShaderStage_Fragment; dble[1].texture.sampleType = WGPUTextureSampleType_Float; dble[1].texture.viewDimension = WGPUTextureViewDimension_2D;
  dble[2].binding = 2; dble[2].visibility = WGPUShaderStage_Fragment; dble[2].sampler.type = WGPUSamplerBindingType_Filtering;
  WGPUBindGroupLayoutDescriptor dbgld = {}; dbgld.entryCount = 3; dbgld.entries = dble;
  c.denoiseBGL = wgpuDeviceCreateBindGroupLayout(device, &dbgld);
  WGPUPipelineLayoutDescriptor dpld = {}; dpld.bindGroupLayoutCount = 1; dpld.bindGroupLayouts = &c.denoiseBGL;
  WGPUPipelineLayout dpl = wgpuDeviceCreatePipelineLayout(device, &dpld);

  WGPUBlendState dblend = {};
  dblend.color.srcFactor = WGPUBlendFactor_One; dblend.color.dstFactor = WGPUBlendFactor_OneMinusSrcAlpha; dblend.color.operation = WGPUBlendOperation_Add;
  dblend.alpha = dblend.color;
  WGPUColorTargetState dtarget = {}; dtarget.format = colorFormat; dtarget.writeMask = WGPUColorWriteMask_All; dtarget.blend = &dblend;
  WGPUDepthStencilState dds = {}; dds.format = kDepthFormat; dds.depthWriteEnabled = false; dds.depthCompare = WGPUCompareFunction_Always;
  dds.stencilFront.compare = WGPUCompareFunction_Always; dds.stencilBack.compare = WGPUCompareFunction_Always;
  dds.stencilReadMask = 0xFFFFFFFFu; dds.stencilWriteMask = 0xFFFFFFFFu;
  WGPUFragmentState dfrag = {}; dfrag.module = c.denoiseModule; dfrag.entryPoint = "fs_main"; dfrag.targetCount = 1; dfrag.targets = &dtarget;
  WGPURenderPipelineDescriptor drpd = {}; drpd.layout = dpl;
  drpd.vertex.module = c.denoiseModule; drpd.vertex.entryPoint = "vs_main";
  drpd.primitive.topology = WGPUPrimitiveTopology_TriangleList;
  drpd.depthStencil = &dds; drpd.multisample.count = 1; drpd.multisample.mask = 0xFFFFFFFFu; drpd.fragment = &dfrag;
  c.denoisePipeline = wgpuDeviceCreateRenderPipeline(device, &drpd);
  wgpuPipelineLayoutRelease(dpl);
  return c;
}

int main(int argc, char** argv) {
  // Flush per line so `[spike] …` progress shows even when piped or killed.
  std::setvbuf(stdout, nullptr, _IOLBF, 0);

  // Model to draw: argv[1] > $SAILSIM_MODEL > the ship (default) > rock > cube.
  const char* modelArg = (argc > 1) ? argv[1] : std::getenv("SAILSIM_MODEL");

  // Optional headless cap: render N frames then exit cleanly (for CI / smoke tests).
  const char* maxFramesEnv = std::getenv("SAILSIM_MAX_FRAMES");
  const long maxFrames = maxFramesEnv ? std::atol(maxFramesEnv) : 0;
  long frame = 0;

  // Headless screenshot: SAILSIM_SHOT=out.png renders to a chosen frame (default
  // 240, so the FFT/foam has settled), writes a PNG, and exits.
  const char* shotPath = std::getenv("SAILSIM_SHOT");
  const long shotFrame = shotPath ? (maxFramesEnv ? maxFrames : 240) : -1;

  // Headless auth round-trip test: exercises net_auth against the live server with
  // no window. SAILSIM_AUTH_TEST=login|register, SAILSIM_AUTH_USER / _PASS / _CALLSIGN.
  // With no user set it posts a bogus login to verify connectivity + error parsing.
  if (const char* authMode = std::getenv("SAILSIM_AUTH_TEST")) {
    const char* host = std::getenv("SAILSIM_HOST"); if (!host) host = "localhost";
    const char* portEnv = std::getenv("SAILSIM_PORT");
    const int port = portEnv ? std::atoi(portEnv) : 9080;
    const char* u  = std::getenv("SAILSIM_AUTH_USER");
    const char* p  = std::getenv("SAILSIM_AUTH_PASS");
    const char* cs = std::getenv("SAILSIM_AUTH_CALLSIGN");
    std::string user = u ? u : "no_such_user_probe";
    std::string pass = p ? p : "definitely_wrong_password";
    const char* tok = std::getenv("SAILSIM_AUTH_TOKEN");
    net::AuthResult r =
        (std::string(authMode) == "register") ? net::registerUser(host, port, user, cs ? cs : user, pass)
      : (std::string(authMode) == "me")       ? net::me(host, port, tok ? tok : "")
      :                                          net::login(host, port, user, pass);
    std::printf("[auth-test] %s %s:%d user=%s -> ok=%d status=%d\n",
                authMode, host, port, user.c_str(), (int)r.ok, r.status);
    if (r.ok) std::printf("[auth-test] callsign=%s role=%s token=%.16s...\n",
                          r.callsign.c_str(), r.role.c_str(), r.token.c_str());
    else      std::printf("[auth-test] error=\"%s\"\n", r.error.c_str());
    return r.ok ? EXIT_SUCCESS : EXIT_FAILURE;
  }

  // Headless WebSocket gameplay test: login, open the socket, exchange a few
  // messages, report what came back. SAILSIM_WS_TEST=1 (+ SAILSIM_AUTH_USER/_PASS).
  if (std::getenv("SAILSIM_WS_TEST")) {
    const char* host = std::getenv("SAILSIM_HOST"); if (!host) host = "localhost";
    const char* portEnv = std::getenv("SAILSIM_PORT");
    const int port = portEnv ? std::atoi(portEnv) : 9080;
    const char* u = std::getenv("SAILSIM_AUTH_USER");
    const char* p = std::getenv("SAILSIM_AUTH_PASS");
    net::AuthResult lr = net::login(host, port, u ? u : "native_probe_01", p ? p : "testpass123");
    if (!lr.ok) { std::printf("[ws-test] login failed: %s\n", lr.error.c_str()); return EXIT_FAILURE; }

    mp::Client c;
    c.connect(host, port, lr.token);
    for (int i = 0; i < 60 && c.state() == mp::ConnState::Connecting; ++i)
      std::this_thread::sleep_for(std::chrono::milliseconds(50));   // await open (<=3s)

    if (c.state() == mp::ConnState::Open) {
      mp::PlayerUpdate pu; pu.x = 10; pu.z = 20; pu.heading = 1.0f; pu.speed = 3.0f;
      pu.sailState = "full"; pu.vesselName = "Merchantman"; pu.vesselSlug = "merchantman";
      pu.callsign = lr.callsign;
      c.sendUpdate(pu, 0);
      std::this_thread::sleep_for(std::chrono::milliseconds(1200));   // let snapshot/wave arrive
    }
    mp::WaveState wv = c.wave();
    std::printf("[ws-test] state=%d myId=%s players=%d wave.valid=%d wind=%.1f beaufort=%d\n",
                (int)c.state(), c.myId().c_str(), (int)c.players().size(),
                (int)wv.valid, wv.windSpeed, wv.beaufort);
    bool ok = (c.state() == mp::ConnState::Open);
    c.close();
    return ok ? EXIT_SUCCESS : EXIT_FAILURE;
  }

  // Headless terrain-data test: fetch + decode the heightfield and sample it.
  if (std::getenv("SAILSIM_TERRAIN_TEST")) {
    const char* host = std::getenv("SAILSIM_HOST"); if (!host) host = "localhost";
    const char* portEnv = std::getenv("SAILSIM_PORT");
    const int port = portEnv ? std::atoi(portEnv) : 9080;
    terrain::Terrain terr;
    if (!terr.load(host, port)) return EXIT_FAILURE;
    const terrain::Manifest& m = terr.manifest();
    std::printf("[terrain-test] origin(0,0) elev=%.1f m (%s)\n",
                terr.elevation(0, 0), terr.isLand(0, 0) ? "LAND" : "water");
    // Sample near the first few harbors — the shore point should read ~0 m.
    for (size_t i = 0; i < m.harbors.size() && i < 4; ++i) {
      const terrain::Harbor& h = m.harbors[i];
      std::printf("[terrain-test] harbor '%s' (%.0f,%.0f) shore=%.1f m  inland+200m=%.1f m\n",
                  h.name.c_str(), h.x, h.z, terr.elevation(h.x, h.z),
                  terr.elevation(h.x, h.z + 200.0f));
    }
    return EXIT_SUCCESS;
  }

#if defined(WEBGPU_BACKEND_WGPU)
  // Surface wgpu-native's internal logs (including WGSL compile errors).
  wgpuSetLogLevel(WGPULogLevel_Warn);
  wgpuSetLogCallback([](WGPULogLevel level, char const* msg, void*) {
    std::fprintf(stderr, "[wgpu] (%d) %s\n", (int)level, msg ? msg : "");
  }, nullptr);
#endif

  // Headless compute-only mode: run the ocean-FFT readback test with no window,
  // then exit 0/1. Ideal for CI or a quick Windows/D3D12 check.
  if (std::getenv("SAILSIM_FFT_ONLY")) {
    WGPUInstanceDescriptor instDesc = {};
    WGPUInstance inst = wgpuCreateInstance(&instDesc);
    WGPURequestAdapterOptions ao = {};
    ao.powerPreference = WGPUPowerPreference_HighPerformance;
    WGPUAdapter ad = requestAdapterSync(inst, &ao);
    if (!ad) return EXIT_FAILURE;
    WGPUAdapterProperties props = {};
    wgpuAdapterGetProperties(ad, &props);
    std::printf("[spike] headless FFT test — backend=%s device=%s\n",
                backendTypeName(props.backendType), props.name ? props.name : "?");
    WGPUDeviceDescriptor dd = {};
    dd.label = "sailsim-device";
    WGPUDevice dev = requestDeviceSync(ad, &dd);
    if (!dev) return EXIT_FAILURE;
    wgpuDeviceSetUncapturedErrorCallback(dev, onDeviceError, nullptr);
    WGPUQueue q = wgpuDeviceGetQueue(dev);
    const bool ok = runInitialSpectrumTest(dev, q);
    wgpuQueueRelease(q);
    wgpuDeviceRelease(dev);
    wgpuAdapterRelease(ad);
    wgpuInstanceRelease(inst);
    return ok ? EXIT_SUCCESS : EXIT_FAILURE;
  }

  if (!glfwInit()) {
    std::fprintf(stderr, "[spike] glfwInit failed\n");
    return EXIT_FAILURE;
  }

  // WebGPU manages the drawing surface; tell GLFW not to create an OpenGL context.
  glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
  GLFWwindow* window = glfwCreateWindow(1280, 720, "sail-sim native — Phase 1: camera + depth", nullptr, nullptr);
  if (!window) {
    std::fprintf(stderr, "[spike] glfwCreateWindow failed\n");
    glfwTerminate();
    return EXIT_FAILURE;
  }
  glfwSetScrollCallback(window, onScroll);   // mouse-wheel zoom

  // 1. Instance
  WGPUInstanceDescriptor instanceDesc = {};
  WGPUInstance instance = wgpuCreateInstance(&instanceDesc);
  if (!instance) {
    std::fprintf(stderr, "[spike] wgpuCreateInstance failed\n");
    return EXIT_FAILURE;
  }

  // 2. Surface (per-OS creation hidden inside glfw3webgpu)
  WGPUSurface surface = glfwGetWGPUSurface(instance, window);

  // 3. Adapter
  WGPURequestAdapterOptions adapterOpts = {};
  adapterOpts.compatibleSurface = surface;
  adapterOpts.powerPreference = WGPUPowerPreference_HighPerformance;
  WGPUAdapter adapter = requestAdapterSync(instance, &adapterOpts);
  if (!adapter) return EXIT_FAILURE;

  // Report which native backend was selected — the visible proof of the thesis.
  // wgpuAdapterGetProperties is present in both wgpu-native and Dawn 6512.
  WGPUAdapterProperties adapterProps = {};
  wgpuAdapterGetProperties(adapter, &adapterProps);
  std::printf("[spike] adapter: backend=%s  vendor=%s  device=%s\n",
              backendTypeName(adapterProps.backendType),
              adapterProps.vendorName ? adapterProps.vendorName : "?",
              adapterProps.name ? adapterProps.name : "?");

  // 4. Device + queue
  WGPUDeviceDescriptor deviceDesc = {};
  deviceDesc.label = "sailsim-device";
  WGPUDevice device = requestDeviceSync(adapter, &deviceDesc);
  if (!device) return EXIT_FAILURE;

  wgpuDeviceSetUncapturedErrorCallback(device, onDeviceError, nullptr);

  WGPUQueue queue = wgpuDeviceGetQueue(device);

  // Phase 0 criteria 3-5: prove the ocean-FFT WGSL runs natively and reads back.
  runInitialSpectrumTest(device, queue);

  // 5. Configure the surface (swapchain)
  WGPUSurfaceCapabilities caps = {};
  wgpuSurfaceGetCapabilities(surface, adapter, &caps);
  WGPUTextureFormat surfaceFormat = caps.formatCount > 0 ? caps.formats[0] : WGPUTextureFormat_BGRA8Unorm;

  int fbWidth = 0, fbHeight = 0;
  glfwGetFramebufferSize(window, &fbWidth, &fbHeight);

  WGPUSurfaceConfiguration surfaceConfig = {};
  surfaceConfig.device = device;
  surfaceConfig.format = surfaceFormat;
  surfaceConfig.usage = WGPUTextureUsage_RenderAttachment;
  surfaceConfig.width = (uint32_t)fbWidth;
  surfaceConfig.height = (uint32_t)fbHeight;
  surfaceConfig.presentMode = WGPUPresentMode_Fifo;   // vsync
  surfaceConfig.alphaMode = WGPUCompositeAlphaMode_Auto;
  if (shotPath) surfaceConfig.usage |= WGPUTextureUsage_CopySrc;   // allow screenshot readback
  wgpuSurfaceConfigure(surface, &surfaceConfig);

  std::printf("[spike] surface configured: %dx%d format=%d — entering render loop\n",
              fbWidth, fbHeight, (int)surfaceFormat);

  // Vessels are loaded lazily by slug and cached — you and remote players share a
  // hull's geometry (one copy), each drawn as its own instance. The owned hull is
  // server-authoritative (arrives in the "wallet" message); a command-line/env
  // model override (SAILSIM_MODEL / argv[1]) forces a specific GLB for testing.
  std::map<std::string, Mesh> vessels;
  auto vesselFor = [&](const std::string& slug) -> Mesh& {
    auto it = vessels.find(slug);
    if (it != vessels.end()) return it->second;
    std::string path = glbForSlug(slug);
    std::printf("[vessel] loading '%s' <- %s\n", slug.c_str(), path.c_str());
    auto res = vessels.emplace(slug, loadVessel(device, queue, surfaceFormat, path));
    return res.first->second;
  };
  std::string ownVesselSlug;
  const bool ownVesselForced = (modelArg != nullptr);
  if (ownVesselForced) {
    vessels.emplace("__cli", loadVessel(device, queue, surfaceFormat, modelArg));
    ownVesselSlug = "__cli";
  }

  Ocean ocean = createOcean(device, queue, surfaceFormat);
  Sky sky = createSky(device, surfaceFormat);
  TerrainRender terrainR = createTerrainRender(device, queue, surfaceFormat);
  SeaFar seaFar = createSeaFar(device, queue, surfaceFormat);
  Clouds clouds = createClouds(device, queue, surfaceFormat);
  glm::vec2 cloudDrift(0.0f);   // accumulated wind drift (metres), integrated per frame
  // Weather state, eased toward Beaufort-driven targets each frame (mirrors the
  // client's cloud.service): cloudiness/storminess shape the clouds, seaAmp the swell.
  float cloudiness = 0.25f, storminess = 0.0f, seaAmp = 1.0f;

  // FFT ocean — 3 cascades (250 / 17 / 5 m tiles) with split cutoff bands so they
  // don't double-count wavelengths. 256² each. Prime one frame + sanity-check.
  const float B1 = 6.2831853f / 17.0f * 6.0f;
  const float B2 = 6.2831853f / 5.0f  * 6.0f;
  OceanFFT c0(device, queue, 256, 250.0f, 0.0001f, B1);
  OceanFFT c1(device, queue, 256, 17.0f,  B1,      B2);
  OceanFFT c2(device, queue, 256, 5.0f,   B2,      9999.0f);
  for (OceanFFT* c : { &c0, &c1, &c2 }) c->initSpectrum();
  // Pre-warm the sim: the turbulence/foam field accumulates only ~0.008/frame in the
  // merger, so it climbs from 0 (which reads as a full-surface whiteout in the foam
  // term) over a few hundred frames. Advance it here so the FIRST visible frame is at
  // steady state — foam on the crests, not the whole sea. ~5 s of sim, runs in a blink.
  for (int i = 0; i < 300; ++i) {
    float wt = (float)i * (1.0f / 60.0f);
    for (OceanFFT* c : { &c0, &c1, &c2 }) c->update(wt, 1.0f / 60.0f);
  }
  c0.sanityCheck();

  uint32_t curW = (uint32_t)fbWidth, curH = (uint32_t)fbHeight;
  WGPUTexture depthTex = makeDepthTexture(device, curW, curH);
  WGPUTextureView depthView = wgpuTextureCreateView(depthTex, nullptr);
  // Planar reflection target (colour + its own depth).
  WGPUTexture reflTex = makeColorRTT(device, curW, curH, surfaceFormat);
  WGPUTextureView reflView = wgpuTextureCreateView(reflTex, nullptr);
  WGPUTexture reflDepth = makeDepthTexture(device, curW, curH);
  WGPUTextureView reflDepthView = wgpuTextureCreateView(reflDepth, nullptr);
  // Offscreen cloud buffer (RGBA16F): the ray march writes here, then the denoise
  // pass filters it onto the frame. Its bind group is rebuilt when it resizes.
  WGPUTexture cloudTex = makeColorRTT(device, curW, curH, kCloudFormat);
  WGPUTextureView cloudView = wgpuTextureCreateView(cloudTex, nullptr);
  auto buildDenoiseBG = [&]() {
    WGPUBindGroupEntry e[3] = {};
    e[0].binding = 0; e[0].buffer = clouds.denoiseUniform; e[0].size = 16;
    e[1].binding = 1; e[1].textureView = cloudView;
    e[2].binding = 2; e[2].sampler = clouds.cloudSamp;
    WGPUBindGroupDescriptor d = {}; d.layout = clouds.denoiseBGL; d.entryCount = 3; d.entries = e;
    return wgpuDeviceCreateBindGroup(device, &d);
  };
  WGPUBindGroup denoiseBG = buildDenoiseBG();

  // Sailing state — arrow keys / WASD steer and trim sail; the ship sails the sea.
  float shipX = 0.0f, shipZ = 0.0f, shipHeading = 0.0f, shipSpeed = 0.0f, sail = 0.35f;
  // The merchantman's model-space forward axis is +X, but travel (fwd) is +Z, so
  // yaw the hull by -90° to line the bow up with the direction of sailing.
  const float kBowYaw = -glm::half_pi<float>();
  // Scale the wave-sim clock. Real-time (1.0) reads as too-fast chop; too slow (~0.45)
  // makes tall waves look gelatinous ("jelly") because they move slower than their
  // steepness implies. 0.6 is the compromise — a calmer swell that still flows.
  const float kWaveSpeed = 0.6f;

  // Orbit camera: chase behind the ship by default; hold LMB + drag to orbit, wheel to
  // zoom. camYawOffset is relative to the heading (0 = directly astern), so the camera
  // keeps chasing as the ship turns while any drag offset is preserved.
  float camYawOffset = 0.0f, camPitch = 0.43f, camDist = 14.3f;
  double lastMouseX = 0.0, lastMouseY = 0.0;
  glfwGetCursorPos(window, &lastMouseX, &lastMouseY);

  // ── Dear ImGui: login screen + in-game HUD ────────────────────────────────
  IMGUI_CHECKVERSION();
  ImGui::CreateContext();
  ImGuiIO& imio = ImGui::GetIO();
  imio.IniFilename = nullptr;   // don't write imgui.ini next to the exe
  // Embedded fonts, rasterised at the display's content scale for crisp text on
  // HiDPI; FontGlobalScale then brings them back to logical size. Inter is the
  // default (body) font; Cinzel is kept for titles (pushed where needed).
  float uiScaleX = 1.0f, uiScaleY = 1.0f;
  glfwGetWindowContentScale(window, &uiScaleX, &uiScaleY);
  if (uiScaleX <= 0.0f) uiScaleX = 1.0f;
  ImFontConfig fontCfg;
  fontCfg.FontDataOwnedByAtlas = false;   // static arrays — don't let ImGui free them
  imio.Fonts->AddFontFromMemoryTTF((void*)UI_FONT_BODY, (int)UI_FONT_BODY_SIZE,
                                   18.0f * uiScaleX, &fontCfg);   // default = body
  ImFont* fontTitle = imio.Fonts->AddFontFromMemoryTTF((void*)UI_FONT_TITLE, (int)UI_FONT_TITLE_SIZE,
                                                       30.0f * uiScaleX, &fontCfg);
  imio.FontGlobalScale = 1.0f / uiScaleX;
  styleSailSim();
  ImGui_ImplGlfw_InitForOther(window, true);
  ImGui_ImplWGPU_InitInfo imguiInit;
  imguiInit.Device = device;
  imguiInit.NumFramesInFlight = 3;
  imguiInit.RenderTargetFormat = surfaceFormat;
  imguiInit.DepthStencilFormat = kDepthFormat;   // must match the main pass's depth attachment
  ImGui_ImplWGPU_Init(&imguiInit);

  // App state: sign in first, then sail. The ocean scene renders behind the login.
  enum class AppState { Login, Connecting, Sailing };
  AppState appState = AppState::Login;
  const std::string kHost = "localhost";
  const int         kPort = 9080;
  char uiUser[64] = "", uiPass[64] = "", uiCallsign[64] = "";
  bool uiRegisterMode = false, uiRemember = false;
  std::string uiError, authToken, authCallsign, authUsername, authRole;
  std::future<net::AuthResult> authFuture;

  // Multiplayer: connected on entering Sailing, closed on logout. Our pose is
  // sent ~10 Hz; remote players/wind arrive on the client's own thread.
  mp::Client mpClient;
  uint32_t netSeq = 0;
  bool mpConnected = false;

  // Terrain: fetch + decode the world heightfield off-thread; upload the height
  // texture and place the ship near land once it arrives.
  terrain::Terrain terr;
  std::future<bool> terrFuture = std::async(std::launch::async,
      [&terr, kHost, kPort] { return terr.load(kHost, kPort); });
  bool terrHandled = false;

  // "Remember me": if a saved session exists, validate its token via /user/me and,
  // if still good, drop the player straight into the game. A 401 clears it.
  session::Saved saved;
  bool restoringSession = false;
  if (session::load(saved)) {
    uiRemember = true;
    restoringSession = true;
    std::strncpy(uiUser, saved.username.c_str(), sizeof(uiUser) - 1);  // prefill if it fails
    appState = AppState::Connecting;
    std::string host = kHost, tok = saved.token;
    int port = kPort;
    authFuture = std::async(std::launch::async, net::me, host, port, tok);
  }

  // 6. Render loop: reflection pass, then sky + ocean + ship.
  while (!glfwWindowShouldClose(window)) {
    glfwPollEvents();
    if (maxFrames > 0 && frame >= maxFrames) break;
    ++frame;

    // Handle window resize: reconfigure the surface and rebuild the depth buffer.
    int w = 0, h = 0;
    glfwGetFramebufferSize(window, &w, &h);
    if (w > 0 && h > 0 && ((uint32_t)w != curW || (uint32_t)h != curH)) {
      curW = (uint32_t)w; curH = (uint32_t)h;
      surfaceConfig.width = curW; surfaceConfig.height = curH;
      wgpuSurfaceConfigure(surface, &surfaceConfig);
      wgpuTextureViewRelease(depthView);
      wgpuTextureRelease(depthTex);
      depthTex = makeDepthTexture(device, curW, curH);
      depthView = wgpuTextureCreateView(depthTex, nullptr);
      wgpuTextureViewRelease(reflView);   wgpuTextureRelease(reflTex);
      wgpuTextureViewRelease(reflDepthView); wgpuTextureRelease(reflDepth);
      reflTex = makeColorRTT(device, curW, curH, surfaceFormat);
      reflView = wgpuTextureCreateView(reflTex, nullptr);
      reflDepth = makeDepthTexture(device, curW, curH);
      reflDepthView = wgpuTextureCreateView(reflDepth, nullptr);
      wgpuTextureViewRelease(cloudView); wgpuTextureRelease(cloudTex);
      cloudTex = makeColorRTT(device, curW, curH, kCloudFormat);
      cloudView = wgpuTextureCreateView(cloudTex, nullptr);
      wgpuBindGroupRelease(denoiseBG);
      denoiseBG = buildDenoiseBG();
    }

    float aspect = (float)curW / (float)curH;
    float t = (float)frame * (1.0f / 60.0f);
    float waveT = t * kWaveSpeed;   // slowed sim clock for the wave fields
    const float dt = 1.0f / 60.0f;

    // Terrain arrived? Upload its height texture and start the ship near a harbour.
    if (!terrHandled && terrFuture.valid() &&
        terrFuture.wait_for(std::chrono::seconds(0)) == std::future_status::ready) {
      if (terrFuture.get() && terr.loaded()) {
        const terrain::Manifest& tm = terr.manifest();
        uploadTerrainHeight(device, queue, terrainR, tm.width, tm.height, terr.field().data());
        if (!tm.harbors.empty()) {
          const terrain::Harbor* best = &tm.harbors[0]; float bestD = 1e30f;
          for (const terrain::Harbor& h : tm.harbors) {
            float d = h.x * h.x + h.z * h.z; if (d < bestD) { bestD = d; best = &h; }
          }
          float hr = glm::radians(best->heading);
          glm::vec3 seaward(std::sin(hr), 0.0f, -std::cos(hr));   // 0=N(-Z), 90=E(+X)
          shipX = best->x + seaward.x * 700.0f;
          shipZ = best->z + seaward.z * 700.0f;
          shipHeading = hr + glm::pi<float>();   // bow toward the harbour
          std::printf("[terrain] start near '%s' at (%.0f, %.0f)\n", best->name.c_str(), shipX, shipZ);
        }
      }
      terrHandled = true;
    }

    // ── Dear ImGui frame: login / HUD ─────────────────────────────────────
    ImGui_ImplWGPU_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();
    ImGuiIO& io = ImGui::GetIO();

    // Resolve an in-flight auth request (posted off-thread so the sea keeps moving).
    if (appState == AppState::Connecting && authFuture.valid() &&
        authFuture.wait_for(std::chrono::seconds(0)) == std::future_status::ready) {
      net::AuthResult res = authFuture.get();
      if (res.ok) {
        authToken = res.token; authUsername = res.username; authRole = res.role;
        // /user/me (session restore) doesn't return the callsign — keep the saved one.
        authCallsign = res.callsign.empty() ? saved.callsign : res.callsign;
        uiError.clear();
        std::memset(uiPass, 0, sizeof(uiPass));
        if (uiRemember) session::save({ authToken, authUsername, authCallsign, authRole });
        mpClient.connect(kHost, kPort, authToken);   // open the gameplay socket
        mpConnected = true;
        appState = AppState::Sailing;
      } else {
        // A rejected token (401/403) clears the remembered session; a mere
        // can't-reach-server (status 0) keeps it for next time.
        if (restoringSession) {
          if (res.status == 401 || res.status == 403) session::clear();
          uiError.clear();   // silent on a background restore
        } else {
          uiError = res.error.empty() ? "Sign-in failed." : res.error;
        }
        appState = AppState::Login;
      }
      restoringSession = false;
    }

    // Login / register panel, centred over the landing screen.
    if (appState == AppState::Login || appState == AppState::Connecting) {
      ImGui::SetNextWindowPos(ImVec2(io.DisplaySize.x * 0.5f, io.DisplaySize.y * 0.5f),
                              ImGuiCond_Always, ImVec2(0.5f, 0.5f));
      ImGui::Begin("##login", nullptr,
                   ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove |
                   ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_AlwaysAutoResize |
                   ImGuiWindowFlags_NoTitleBar);
      const float fieldW = 300.0f;
      // Nudge the cursor so the next single-line item is centred in the content area.
      auto center = [&](const char* s) {
        float avail = ImGui::GetContentRegionAvail().x, tw = ImGui::CalcTextSize(s).x;
        if (avail > tw) ImGui::SetCursorPosX(ImGui::GetCursorPosX() + (avail - tw) * 0.5f);
      };

      ImGui::PushFont(fontTitle);
      center("SAIL-SIM"); ImGui::TextUnformatted("SAIL-SIM");
      ImGui::PopFont();
      const char* sub = uiRegisterMode ? "Create your account" : "Sign in to set sail";
      center(sub); ImGui::TextDisabled("%s", sub);
      ImGui::Dummy(ImVec2(0, 8));

      const bool busy = (appState == AppState::Connecting);
      ImGui::BeginDisabled(busy);
      ImGui::SetNextItemWidth(fieldW);
      ImGui::InputTextWithHint("##user", "Username", uiUser, sizeof(uiUser));
      if (uiRegisterMode) {
        ImGui::SetNextItemWidth(fieldW);
        ImGui::InputTextWithHint("##callsign", "Callsign", uiCallsign, sizeof(uiCallsign));
      }
      ImGui::SetNextItemWidth(fieldW);
      ImGui::InputTextWithHint("##pass", "Password", uiPass, sizeof(uiPass), ImGuiInputTextFlags_Password);
      ImGui::Checkbox("Remember me", &uiRemember);
      ImGui::Dummy(ImVec2(0, 4));

      const bool canSubmit = uiUser[0] && uiPass[0] && (!uiRegisterMode || uiCallsign[0]);
      ImGui::BeginDisabled(!canSubmit);
      if (ImGui::Button(uiRegisterMode ? "Create account" : "Log in", ImVec2(fieldW, 0))) {
        uiError.clear();
        std::string u = uiUser, p = uiPass, cs = uiCallsign, host = kHost;
        int port = kPort;
        authFuture = uiRegisterMode
          ? std::async(std::launch::async, net::registerUser, host, port, u, cs, p)
          : std::async(std::launch::async, net::login, host, port, u, p);
        appState = AppState::Connecting;
      }
      ImGui::EndDisabled();

      const char* toggle = uiRegisterMode ? "Back to sign in" : "Create an account";
      const float bw = 200.0f;
      ImGui::SetCursorPosX(ImGui::GetCursorPosX() + (fieldW - bw) * 0.5f);
      if (ImGui::Button(toggle, ImVec2(bw, 0))) uiRegisterMode = !uiRegisterMode;
      ImGui::EndDisabled();   // busy

      ImGui::Dummy(ImVec2(0, 2));
      if (busy) { center("Connecting..."); ImGui::TextUnformatted("Connecting..."); }
      if (!uiError.empty()) { center(uiError.c_str());
        ImGui::TextColored(ImVec4(0.95f, 0.45f, 0.45f, 1.0f), "%s", uiError.c_str()); }
      char srv[96]; std::snprintf(srv, sizeof(srv), "server: %s:%d", kHost.c_str(), kPort);
      center(srv); ImGui::TextDisabled("%s", srv);
      ImGui::End();
    }

    // A dropped/expired gameplay token (ws close 4401) forces re-login.
    if (appState == AppState::Sailing && mpClient.state() == mp::ConnState::AuthFailed) {
      mpClient.close(); mpConnected = false;
      session::clear();
      authToken.clear(); authCallsign.clear(); authUsername.clear(); authRole.clear();
      uiError = "Session expired - please sign in again.";
      appState = AppState::Login;
    }

    // In-game HUD: identity, connection, nearby players, wind.
    if (appState == AppState::Sailing) {
      const mp::ConnState cs = mpClient.state();
      std::vector<mp::RemotePlayer> others = mpClient.players();
      mp::WaveState wv = mpClient.wave();

      ImGui::SetNextWindowPos(ImVec2(12, 12), ImGuiCond_Always);
      ImGui::Begin("hud", nullptr, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove |
                   ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoTitleBar);
      ImGui::Text("Callsign: %s", authCallsign.empty() ? authUsername.c_str() : authCallsign.c_str());
      ImGui::Text("Speed: %.1f kn", shipSpeed);

      const char* connLabel =
          cs == mp::ConnState::Open       ? "connected" :
          cs == mp::ConnState::Connecting ? "connecting..." :
          cs == mp::ConnState::AuthFailed ? "auth failed" : "offline";
      const ImVec4 connCol = cs == mp::ConnState::Open ? ImVec4(0.45f, 0.85f, 0.55f, 1.0f)
                                                       : ImVec4(0.90f, 0.70f, 0.40f, 1.0f);
      ImGui::TextColored(connCol, "Server: %s", connLabel);
      if (wv.valid) ImGui::Text("Wind: %.0f kn  Beaufort %d", wv.windSpeed, wv.beaufort);

      ImGui::Separator();
      ImGui::Text("Players nearby: %d", (int)others.size());
      for (const mp::RemotePlayer& rp : others) {
        const char* who = !rp.callsign.empty() ? rp.callsign.c_str() : rp.id.c_str();
        ImGui::BulletText("%s  (%.0f, %.0f)", who, rp.x, rp.z);
      }

      ImGui::Separator();
      if (ImGui::Button("Log out")) {
        mpClient.close(); mpConnected = false;
        session::clear();   // forget the remembered session
        authToken.clear(); authCallsign.clear(); authUsername.clear(); authRole.clear();
        uiError.clear();
        appState = AppState::Login;
      }
      ImGui::End();

      // Broadcast our pose ~10 Hz.
      if (cs == mp::ConnState::Open && (frame % 6) == 0) {
        const char* sailState = sail > 0.66f ? "full" : (sail > 0.33f ? "half" : "furled");
        mp::PlayerUpdate pu;
        pu.x = shipX; pu.z = shipZ; pu.heading = shipHeading; pu.speed = shipSpeed;
        pu.sailState = sailState; pu.vesselName = "Merchantman"; pu.vesselSlug = "merchantman";
        pu.callsign = authCallsign;
        mpClient.sendUpdate(pu, netSeq++);
      }
    }
    ImGui::Render();

    // Sailing input + physics — only while actually sailing and ImGui isn't typing.
    // (sail 0..1 sets target speed; heading turns with rudder authority scaled by way.)
    glm::vec3 fwd(std::sin(shipHeading), 0.0f, std::cos(shipHeading));
    if (appState == AppState::Sailing && !io.WantCaptureKeyboard) {
      auto down = [&](int k1, int k2) { return glfwGetKey(window, k1) == GLFW_PRESS || glfwGetKey(window, k2) == GLFW_PRESS; };
      float turn = (down(GLFW_KEY_A, GLFW_KEY_LEFT) ? 1.0f : 0.0f) - (down(GLFW_KEY_D, GLFW_KEY_RIGHT) ? 1.0f : 0.0f);
      float trim = (down(GLFW_KEY_W, GLFW_KEY_UP)    ? 1.0f : 0.0f) - (down(GLFW_KEY_S, GLFW_KEY_DOWN) ? 1.0f : 0.0f);
      sail = glm::clamp(sail + trim * 0.4f * dt, 0.0f, 1.0f);
      shipHeading += turn * 0.7f * dt * (0.4f + 0.6f * glm::clamp(shipSpeed / 6.0f, 0.0f, 1.0f));
      float targetSpeed = sail * 9.0f;
      shipSpeed += (targetSpeed - shipSpeed) * 0.6f * dt;
      fwd = glm::vec3(std::sin(shipHeading), 0.0f, std::cos(shipHeading));
      shipX += fwd.x * shipSpeed * dt;
      shipZ += fwd.z * shipSpeed * dt;
    }

    // Advance all cascades, then read their displacement back so buoyancy is driven
    // by the REAL FFT surface (not the analytic Gerstner field). Only while sailing —
    // the login/landing screen draws no scene, so there's nothing to simulate.
    const bool sailing = (appState == AppState::Sailing);
    if (sailing) {
      c0.update(waveT, 1.0f / 60.0f);
      c1.update(waveT, 1.0f / 60.0f);
      c2.update(waveT, 1.0f / 60.0f);
      c0.readbackDisplacement();
      c1.readbackDisplacement();
      c2.readbackDisplacement();
    }

    // Weather: ease cloudiness/storminess/sea amplitude toward Beaufort-driven
    // targets (server wave_state). Sea amplitude scales the FFT swell + buoyancy.
    {
      mp::WaveState wv = mpClient.wave();
      float beau = wv.valid ? (float)wv.beaufort : 3.0f;
      if (const char* bo = std::getenv("SAILSIM_BEAUFORT")) beau = (float)std::atof(bo);   // debug override
      float targetCloud = glm::clamp(0.18f + beau * 0.080f, 0.0f, 0.97f);
      float targetStorm = glm::clamp((beau - 4.0f) / 6.0f, 0.0f, 1.0f);
      cloudiness += (targetCloud - cloudiness) * glm::min(1.0f, dt * 0.70f);
      storminess += (targetStorm - storminess) * glm::min(1.0f, dt * 0.55f);
      seaAmp      = glm::clamp(0.45f + beau * 0.19f, 0.45f, 2.2f);   // Beaufort 3 ~= 1.0
    }

    // Water height at a world (x,z) = summed vertical displacement, wind-scaled.
    auto fftHeight = [&](float x, float z) {
      float dx, dy, dz, h = 0.0f;
      c0.sampleDisplacement(x, z, dx, dy, dz); h += dy;
      c1.sampleDisplacement(x, z, dx, dy, dz); h += dy;
      c2.sampleDisplacement(x, z, dx, dy, dz); h += dy;
      return h * seaAmp;
    };

    // Camera input: hold LMB + drag to orbit, wheel to zoom.
    double mx = 0.0, my = 0.0;
    glfwGetCursorPos(window, &mx, &my);
    double mdx = mx - lastMouseX, mdy = my - lastMouseY;
    lastMouseX = mx; lastMouseY = my;
    const bool camActive = (appState == AppState::Sailing);
    if (camActive && !io.WantCaptureMouse &&
        glfwGetMouseButton(window, GLFW_MOUSE_BUTTON_LEFT) == GLFW_PRESS) {
      camYawOffset -= (float)mdx * 0.005f;   // drag right -> orbit right
      camPitch     -= (float)mdy * 0.005f;   // drag up    -> look from higher
      camPitch = glm::clamp(camPitch, 0.05f, 1.45f);
    }
    if (g_scrollAccum != 0.0) {
      if (camActive && !io.WantCaptureMouse) {
        camDist *= std::pow(0.9f, (float)g_scrollAccum);   // wheel up -> zoom in
        camDist = glm::clamp(camDist, 4.0f, 80.0f);
      }
      g_scrollAccum = 0.0;
    }

    // Orbit camera: astern of the ship (offset by camYawOffset), pitched up, at camDist.
    float shipY = fftHeight(shipX, shipZ);
    glm::vec3 shipPos(shipX, shipY, shipZ);
    glm::vec3 back = glm::normalize(glm::vec3(glm::rotate(glm::mat4(1.0f), camYawOffset, glm::vec3(0, 1, 0)) * glm::vec4(-fwd, 0.0f)));
    glm::vec3 eye = shipPos + back * (camDist * std::cos(camPitch)) + glm::vec3(0.0f, camDist * std::sin(camPitch), 0.0f);
    glm::mat4 viewM = glm::lookAt(eye, shipPos + glm::vec3(0.0f, 1.0f, 0.0f), glm::vec3(0, 1, 0));
    glm::mat4 proj  = glm::perspective(glm::radians(55.0f), aspect, 0.1f, 2000.0f);
    glm::mat4 viewProj = proj * viewM;

    // Our hull is server-authoritative — adopt the slug from the "wallet" message
    // (unless a CLI/env model override forced one).
    if (!ownVesselForced) {
      std::string s = mpClient.ownedShip();
      if (!s.empty()) ownVesselSlug = s;
    }

    // Place a ship on the wave field: heave to the surface, tilt to its normal
    // (central differences of the FFT height, ~2 m step), yaw to heading, then
    // scale + keel-align per that hull.
    auto shipModel = [&](float x, float z, float heading, const Mesh& m) {
      float y = fftHeight(x, z);
      const float ee = 2.0f;
      float gx = fftHeight(x + ee, z) - fftHeight(x - ee, z);
      float gz = fftHeight(x, z + ee) - fftHeight(x, z - ee);
      glm::vec3 up = glm::normalize(glm::vec3(-gx / (2.0f * ee), 1.0f, -gz / (2.0f * ee)));
      glm::mat4 mm = glm::translate(glm::mat4(1.0f), glm::vec3(x, y - m.draft, z));
      glm::vec3 axis = glm::cross(glm::vec3(0, 1, 0), up);
      float axisLen = glm::length(axis);
      if (axisLen > 1e-5f)
        mm = mm * glm::rotate(glm::mat4(1.0f), std::asin(glm::clamp(axisLen, 0.0f, 1.0f)), axis / axisLen);
      mm = glm::rotate(mm, heading + kBowYaw, glm::vec3(0, 1, 0));
      mm = glm::scale(mm, glm::vec3(m.shipScale));
      mm = glm::translate(mm, -m.keelCenter);
      return mm;
    };

    // Draw list: our ship first (so it takes reflection slot 0), then remote players.
    struct ShipInst { Mesh* mesh; glm::mat4 model; };
    std::vector<ShipInst> ships;
    Mesh* ownMesh = nullptr;
    if (sailing && !ownVesselSlug.empty()) {
      ownMesh = &vesselFor(ownVesselSlug);
      ships.push_back({ ownMesh, shipModel(shipX, shipZ, shipHeading, *ownMesh) });
    }
    if (sailing) {
      for (const mp::RemotePlayer& rp : mpClient.players()) {
        Mesh& rmv = vesselFor(rp.vesselSlug.empty() ? "pinnace" : rp.vesselSlug);
        ships.push_back({ &rmv, shipModel(rp.x, rp.z, rp.heading, rmv) });
      }
    }

    const glm::vec3 sun(0.5f, 1.0f, 0.4f);

    // ── Reflection pass: sky + ship through a mirror camera (reflected across y=0),
    //    rendered into reflView. Queue-ordered uniform writes let one buffer serve
    //    both passes. Skipped on the landing screen. ──
    if (sailing) {
      glm::mat4 mirror = glm::scale(glm::mat4(1.0f), glm::vec3(1.0f, -1.0f, 1.0f));
      glm::mat4 reflVP = proj * viewM * mirror;
      glm::vec3 reflEye(eye.x, -eye.y, eye.z);
      SkyUniform rs{ glm::inverse(reflVP), glm::vec4(reflEye, 1.0f), glm::vec4(sun, 0.0f) };
      wgpuQueueWriteBuffer(queue, sky.uniformBuf, 0, &rs, sizeof(rs));
      if (ownMesh) {
        MeshUniforms rm{ reflVP * ships[0].model, ships[0].model, glm::vec4(reflEye, 1.0f) };
        wgpuQueueWriteBuffer(queue, ownMesh->uniformBuf, 0, &rm, sizeof(rm));   // slot 0
      }

      WGPUCommandEncoder renc = wgpuDeviceCreateCommandEncoder(device, nullptr);
      WGPURenderPassColorAttachment rc = {};
      rc.view = reflView; rc.loadOp = WGPULoadOp_Clear; rc.storeOp = WGPUStoreOp_Store;
      rc.clearValue = WGPUColor{ 0.55, 0.72, 0.88, 1.0 };
      WGPURenderPassDepthStencilAttachment rd = {};
      rd.view = reflDepthView; rd.depthLoadOp = WGPULoadOp_Clear; rd.depthStoreOp = WGPUStoreOp_Store; rd.depthClearValue = 1.0f;
      WGPURenderPassDescriptor rp_desc = {};
      rp_desc.colorAttachmentCount = 1; rp_desc.colorAttachments = &rc; rp_desc.depthStencilAttachment = &rd;
      WGPURenderPassEncoder rp = wgpuCommandEncoderBeginRenderPass(renc, &rp_desc);
      wgpuRenderPassEncoderSetPipeline(rp, sky.pipeline);
      wgpuRenderPassEncoderSetBindGroup(rp, 0, sky.bindGroup, 0, nullptr);
      wgpuRenderPassEncoderDraw(rp, 3, 1, 0, 0);
      if (ownMesh) {
        uint32_t zeroOff = 0;
        wgpuRenderPassEncoderSetPipeline(rp, ownMesh->pipeline);
        wgpuRenderPassEncoderSetVertexBuffer(rp, 0, ownMesh->vbuf, 0, WGPU_WHOLE_SIZE);
        wgpuRenderPassEncoderSetIndexBuffer(rp, ownMesh->ibuf, WGPUIndexFormat_Uint32, 0, WGPU_WHOLE_SIZE);
        for (size_t i = 0; i < ownMesh->submeshes.size(); ++i) {
          wgpuRenderPassEncoderSetBindGroup(rp, 0, ownMesh->bindGroups[i], 1, &zeroOff);
          wgpuRenderPassEncoderDrawIndexed(rp, ownMesh->submeshes[i].indexCount, 1, ownMesh->submeshes[i].indexOffset, 0, 0);
        }
      }
      wgpuRenderPassEncoderEnd(rp);
      wgpuRenderPassEncoderRelease(rp);
      WGPUCommandBuffer rcmd = wgpuCommandEncoderFinish(renc, nullptr);
      wgpuQueueSubmit(queue, 1, &rcmd);
      wgpuCommandBufferRelease(rcmd);
      wgpuCommandEncoderRelease(renc);
    }

    // ── Main-pass uniforms ──
    OceanCamera oc{ viewProj, glm::vec4(eye, 1.0f),
                    glm::vec4(c0.lengthScale(), c1.lengthScale(), c2.lengthScale(), seaAmp),
                    glm::vec4((float)curW, (float)curH, shipX, shipZ) };   // zw = ocean origin (follows ship)
    wgpuQueueWriteBuffer(queue, ocean.uniformBuf, 0, &oc, sizeof(oc));
    SkyUniform sku{ glm::inverse(viewProj), glm::vec4(eye, 1.0f), glm::vec4(sun, 0.0f) };
    wgpuQueueWriteBuffer(queue, sky.uniformBuf, 0, &sku, sizeof(sku));
    if (terrainR.ready) {
      const terrain::Manifest& tm = terr.manifest();
      TerrainU tu{ viewProj, glm::vec4(eye, 1.0f),
                   glm::vec4((float)tm.minX, (float)tm.maxX, (float)tm.minZ, (float)tm.maxZ),
                   glm::vec4((float)tm.width, (float)tm.height, shipX, shipZ),
                   glm::vec4(sun, 0.0f) };
      wgpuQueueWriteBuffer(queue, terrainR.uniformBuf, 0, &tu, sizeof(tu));
    }
    SeaFarU sfu{ viewProj, glm::vec4(eye, 1.0f), glm::vec4(sun, 0.0f),
                 glm::vec4(shipX, shipZ, 290.0f, 0.0f) };
    wgpuQueueWriteBuffer(queue, seaFar.uniformBuf, 0, &sfu, sizeof(sfu));
    // Clouds: integrate wind drift, derive time-of-day light, write uniforms. The
    // sun/sky/ground colour model + coverage/type mirror the client's cloud plugin.
    {
      mp::WaveState wv = mpClient.wave();
      float windSpeed = wv.valid ? wv.windSpeed : 0.0f;
      float windRad = glm::radians(wv.windBearing);
      cloudDrift += glm::vec2(std::sin(windRad), std::cos(windRad)) * (windSpeed * 0.08f * dt);
      glm::vec3 sd = glm::normalize(sun);
      float el = glm::max(0.0f, sd.y);
      // Coverage/type/base from the eased weather state (client's cloud.service model).
      float cov = std::pow(cloudiness, 1.8f);
      float ctype = 0.40f + storminess * 0.55f;
      float cloudBase = 900.0f - storminess * 220.0f;
      float cloudTop = cloudBase + (600.0f + storminess * 700.0f);
      float sunBright = 0.05f + 1.7f * el;
      glm::vec3 sunCol(sunBright, sunBright * (0.52f + 0.48f * el), sunBright * (0.34f + 0.62f * el));
      float stormDim = glm::max(0.08f, 1.0f - glm::max(0.0f, cov - 0.45f) * 1.5f);
      glm::vec3 skyC(stormDim * (0.12f + 1.8f * el), stormDim * (0.15f + 1.9f * el), stormDim * (0.20f + 2.0f * el));
      glm::vec3 grndC(stormDim * (0.05f + 0.16f * el), stormDim * (0.07f + 0.20f * el), stormDim * (0.09f + 0.26f * el));
      CloudU cu{ glm::inverse(viewProj), glm::vec4(eye, 1.0f), glm::vec4(sd, 0.0f),
                 glm::vec4(sunCol, 0.0f), glm::vec4(skyC, 0.0f), glm::vec4(grndC, 0.0f),
                 glm::vec4(cloudBase, cloudTop, cov, ctype),
                 glm::vec4(t, cloudDrift.x, cloudDrift.y, 120000.0f) };
      wgpuQueueWriteBuffer(queue, clouds.uniformBuf, 0, &cu, sizeof(cu));
    }
    // Every ship's uniforms into its vessel's dynamic-offset slots (same per-mesh
    // ordering as the draw loop below, so slot indices line up).
    {
      std::map<Mesh*, uint32_t> slot;
      for (const ShipInst& s : ships) {
        uint32_t idx = slot[s.mesh];
        if (idx >= kMaxShipInstances) continue;
        MeshUniforms mu{ viewProj * s.model, s.model, glm::vec4(eye, 1.0f) };
        wgpuQueueWriteBuffer(queue, s.mesh->uniformBuf,
                             (uint64_t)idx * s.mesh->uniformStride, &mu, sizeof(mu));
        slot[s.mesh] = idx + 1;
      }
    }

    WGPUSurfaceTexture surfaceTex;
    wgpuSurfaceGetCurrentTexture(surface, &surfaceTex);
    if (!surfaceTex.texture) continue;  // e.g. minimised / needs reconfigure

    WGPUTextureView view = wgpuTextureCreateView(surfaceTex.texture, nullptr);

    WGPUCommandEncoderDescriptor encDesc = {};
    WGPUCommandEncoder encoder = wgpuDeviceCreateCommandEncoder(device, &encDesc);

    WGPURenderPassColorAttachment colorAttachment = {};
    colorAttachment.view = view;
    colorAttachment.loadOp = WGPULoadOp_Clear;
    colorAttachment.storeOp = WGPUStoreOp_Store;
    // Sky-blue behind the sailing scene; plain brown behind the login/landing screen.
    colorAttachment.clearValue = sailing ? WGPUColor{0.75, 0.85, 0.92, 1.0}
                                         : WGPUColor{0.24, 0.16, 0.10, 1.0};
    // (Newer webgpu.h adds colorAttachment.depthSlice = WGPU_DEPTH_SLICE_UNDEFINED here;
    //  wgpu-native v0.19 has no such field — zero-init leaves it correctly unset.)

    WGPURenderPassDepthStencilAttachment depthAttachment = {};
    depthAttachment.view = depthView;
    depthAttachment.depthLoadOp = WGPULoadOp_Clear;
    depthAttachment.depthStoreOp = WGPUStoreOp_Store;
    depthAttachment.depthClearValue = 1.0f;

    WGPURenderPassDescriptor passDesc = {};
    passDesc.colorAttachmentCount = 1;
    passDesc.colorAttachments = &colorAttachment;
    passDesc.depthStencilAttachment = &depthAttachment;

    WGPURenderPassEncoder pass = wgpuCommandEncoderBeginRenderPass(encoder, &passDesc);
    WGPUBindGroup oceanBG = nullptr;   // created below only when the scene draws
    if (sailing) {
    // Sky first (background; doesn't write depth).
    wgpuRenderPassEncoderSetPipeline(pass, sky.pipeline);
    wgpuRenderPassEncoderSetBindGroup(pass, 0, sky.bindGroup, 0, nullptr);
    wgpuRenderPassEncoderDraw(pass, 3, 1, 0, 0);

    // Terrain (islands) — displaced height grid, depth-tested against the water.
    if (terrainR.ready) {
      wgpuRenderPassEncoderSetPipeline(pass, terrainR.pipeline);
      wgpuRenderPassEncoderSetBindGroup(pass, 0, terrainR.bindGroup, 0, nullptr);
      wgpuRenderPassEncoderSetVertexBuffer(pass, 0, terrainR.vbuf, 0, WGPU_WHOLE_SIZE);
      wgpuRenderPassEncoderSetIndexBuffer(pass, terrainR.ibuf, WGPUIndexFormat_Uint32, 0, WGPU_WHOLE_SIZE);
      wgpuRenderPassEncoderDrawIndexed(pass, terrainR.indexCount, 1, 0, 0, 0);
    }
    // Far sea (flat distant water; discards the FFT-patch centre near the ship).
    wgpuRenderPassEncoderSetPipeline(pass, seaFar.pipeline);
    wgpuRenderPassEncoderSetBindGroup(pass, 0, seaFar.bindGroup, 0, nullptr);
    wgpuRenderPassEncoderSetVertexBuffer(pass, 0, seaFar.vbuf, 0, WGPU_WHOLE_SIZE);
    wgpuRenderPassEncoderDraw(pass, 6, 1, 0, 0);

    // Ocean surface — bind group references this frame's (ping-ponged) cascade textures.
    WGPUBindGroupEntry oe[12] = {};
    oe[0].binding = 0;  oe[0].buffer = ocean.uniformBuf; oe[0].size = sizeof(OceanCamera);
    oe[1].binding = 1;  oe[1].textureView  = c0.displacement();
    oe[2].binding = 2;  oe[2].textureView  = c0.derivatives();
    oe[3].binding = 3;  oe[3].textureView  = c0.turbulence();
    oe[4].binding = 4;  oe[4].textureView  = c1.displacement();
    oe[5].binding = 5;  oe[5].textureView  = c1.derivatives();
    oe[6].binding = 6;  oe[6].textureView  = c1.turbulence();
    oe[7].binding = 7;  oe[7].textureView  = c2.displacement();
    oe[8].binding = 8;  oe[8].textureView  = c2.derivatives();
    oe[9].binding = 9;  oe[9].textureView  = c2.turbulence();
    oe[10].binding = 10; oe[10].sampler = ocean.sampler;
    oe[11].binding = 11; oe[11].textureView = reflView;
    WGPUBindGroupDescriptor obd = {};
    obd.layout = ocean.bgl; obd.entryCount = 12; obd.entries = oe;
    oceanBG = wgpuDeviceCreateBindGroup(device, &obd);

    wgpuRenderPassEncoderSetPipeline(pass, ocean.pipeline);
    wgpuRenderPassEncoderSetBindGroup(pass, 0, oceanBG, 0, nullptr);
    wgpuRenderPassEncoderSetVertexBuffer(pass, 0, ocean.vbuf, 0, WGPU_WHOLE_SIZE);
    wgpuRenderPassEncoderSetIndexBuffer(pass, ocean.ibuf, WGPUIndexFormat_Uint32, 0, WGPU_WHOLE_SIZE);
    wgpuRenderPassEncoderDrawIndexed(pass, ocean.indexCount, 1, 0, 0, 0);

    // Ships: one draw per instance, each selecting its uniform slot via dynamic offset.
    {
      std::map<Mesh*, uint32_t> slot;
      for (const ShipInst& s : ships) {
        Mesh* m = s.mesh;
        uint32_t idx = slot[m];
        if (idx >= kMaxShipInstances) continue;
        uint32_t dynOff = idx * m->uniformStride;
        wgpuRenderPassEncoderSetPipeline(pass, m->pipeline);
        wgpuRenderPassEncoderSetVertexBuffer(pass, 0, m->vbuf, 0, WGPU_WHOLE_SIZE);
        wgpuRenderPassEncoderSetIndexBuffer(pass, m->ibuf, WGPUIndexFormat_Uint32, 0, WGPU_WHOLE_SIZE);
        for (size_t i = 0; i < m->submeshes.size(); ++i) {
          const Submesh& sm = m->submeshes[i];
          wgpuRenderPassEncoderSetBindGroup(pass, 0, m->bindGroups[i], 1, &dynOff);
          wgpuRenderPassEncoderDrawIndexed(pass, sm.indexCount, 1, sm.indexOffset, 0, 0);
        }
        slot[m] = idx + 1;
      }
    }

    }  // end if (sailing) scene draws
    wgpuRenderPassEncoderEnd(pass);
    wgpuRenderPassEncoderRelease(pass);

    // ── Cloud pass: ray-march into the offscreen RGBA16F buffer, occluded by the
    //    scene depth (load, no write). Only while sailing. ──
    if (sailing) {
      float dsz[4] = { (float)curW, (float)curH, 0.0f, 0.0f };
      wgpuQueueWriteBuffer(queue, clouds.denoiseUniform, 0, dsz, sizeof(dsz));
      WGPURenderPassColorAttachment ca = {};
      ca.view = cloudView; ca.loadOp = WGPULoadOp_Clear; ca.storeOp = WGPUStoreOp_Store;
      ca.clearValue = WGPUColor{ 0.0, 0.0, 0.0, 0.0 };
      WGPURenderPassDepthStencilAttachment da = {};
      da.view = depthView; da.depthLoadOp = WGPULoadOp_Load; da.depthStoreOp = WGPUStoreOp_Store;
      WGPURenderPassDescriptor cpd = {};
      cpd.colorAttachmentCount = 1; cpd.colorAttachments = &ca; cpd.depthStencilAttachment = &da;
      WGPURenderPassEncoder cp = wgpuCommandEncoderBeginRenderPass(encoder, &cpd);
      wgpuRenderPassEncoderSetPipeline(cp, clouds.pipeline);
      wgpuRenderPassEncoderSetBindGroup(cp, 0, clouds.bindGroup, 0, nullptr);
      wgpuRenderPassEncoderDraw(cp, 3, 1, 0, 0);
      wgpuRenderPassEncoderEnd(cp);
      wgpuRenderPassEncoderRelease(cp);
    }

    // ── Final pass: denoise-composite the clouds over the scene (sailing), then
    //    Dear ImGui (login panel / HUD) on top. ──
    {
      WGPURenderPassColorAttachment ca = {};
      ca.view = view; ca.loadOp = WGPULoadOp_Load; ca.storeOp = WGPUStoreOp_Store;
      WGPURenderPassDepthStencilAttachment da = {};
      da.view = depthView; da.depthLoadOp = WGPULoadOp_Load; da.depthStoreOp = WGPUStoreOp_Store;
      WGPURenderPassDescriptor fpd = {};
      fpd.colorAttachmentCount = 1; fpd.colorAttachments = &ca; fpd.depthStencilAttachment = &da;
      WGPURenderPassEncoder fp = wgpuCommandEncoderBeginRenderPass(encoder, &fpd);
      if (sailing) {
        wgpuRenderPassEncoderSetPipeline(fp, clouds.denoisePipeline);
        wgpuRenderPassEncoderSetBindGroup(fp, 0, denoiseBG, 0, nullptr);
        wgpuRenderPassEncoderDraw(fp, 3, 1, 0, 0);
      }
      ImGui_ImplWGPU_RenderDrawData(ImGui::GetDrawData(), fp);
      wgpuRenderPassEncoderEnd(fp);
      wgpuRenderPassEncoderRelease(fp);
    }

    WGPUCommandBufferDescriptor cmdDesc = {};
    WGPUCommandBuffer cmd = wgpuCommandEncoderFinish(encoder, &cmdDesc);
    wgpuQueueSubmit(queue, 1, &cmd);

    if (shotPath && frame == shotFrame) {
      captureSurface(device, queue, surfaceTex.texture, curW, curH, shotPath);
      glfwSetWindowShouldClose(window, GLFW_TRUE);
    }

    wgpuCommandBufferRelease(cmd);
    wgpuCommandEncoderRelease(encoder);
    if (oceanBG) wgpuBindGroupRelease(oceanBG);
    wgpuTextureViewRelease(view);

#ifndef __EMSCRIPTEN__
    wgpuSurfacePresent(surface);
#endif

    // Let Dawn/wgpu service their internal work queues each frame.
#if defined(WEBGPU_BACKEND_DAWN)
    wgpuDeviceTick(device);
#elif defined(WEBGPU_BACKEND_WGPU)
    wgpuDevicePoll(device, false, nullptr);
#endif
  }

  std::printf("[spike] render loop exited after %ld frames — tearing down cleanly\n", frame);

  // 7. Teardown
  wgpuTextureViewRelease(depthView);
  wgpuTextureRelease(depthTex);
  wgpuTextureViewRelease(reflView);      wgpuTextureRelease(reflTex);
  wgpuTextureViewRelease(reflDepthView); wgpuTextureRelease(reflDepth);
  wgpuRenderPipelineRelease(sky.pipeline);
  wgpuBindGroupRelease(sky.bindGroup);
  wgpuBufferRelease(sky.uniformBuf);
  wgpuShaderModuleRelease(sky.module);
  wgpuRenderPipelineRelease(ocean.pipeline);
  wgpuSamplerRelease(ocean.sampler);
  wgpuBufferRelease(ocean.vbuf);
  wgpuBufferRelease(ocean.ibuf);
  wgpuBufferRelease(ocean.uniformBuf);
  wgpuShaderModuleRelease(ocean.module);
  for (auto& kv : vessels) {
    Mesh& m = kv.second;
    wgpuRenderPipelineRelease(m.pipeline);
    for (WGPUBindGroup bg : m.bindGroups) wgpuBindGroupRelease(bg);
    for (WGPUTextureView v : m.views) wgpuTextureViewRelease(v);
    for (WGPUTexture t : m.textures) wgpuTextureRelease(t);
    wgpuSamplerRelease(m.sampler);
    wgpuBufferRelease(m.vbuf);
    wgpuBufferRelease(m.ibuf);
    wgpuBufferRelease(m.uniformBuf);
    wgpuShaderModuleRelease(m.module);
  }
  ImGui_ImplWGPU_Shutdown();
  ImGui_ImplGlfw_Shutdown();
  ImGui::DestroyContext();
  wgpuQueueRelease(queue);
  wgpuDeviceRelease(device);
  wgpuAdapterRelease(adapter);
  wgpuSurfaceRelease(surface);
  wgpuInstanceRelease(instance);
  glfwDestroyWindow(window);
  glfwTerminate();
  return EXIT_SUCCESS;
}
