name: CI Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    if: github.actor != 'dependabot[bot]'   # <-- Skip job for Dependabot
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 127.0.0.1:5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update git submodules
        run: git submodule update --remote --recursive

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up Docker Compose
        run: docker-compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          docker exec jesuit-catalogs-nodejs-prod-1 sh -c "chmod +x wait-for-mysql.sh && ./wait-for-mysql.sh"

      - name: Run tests inside Docker container
        run: |
          docker exec $(docker-compose ps -q nodejs-prod) sh -c "npm test"

      - name: Tear down Docker containers
        run: docker-compose down